"""
app_wildcard_sim.py
===================

CANDIDATE 3 WILDCARD — Industry application falsification experiment.

INDUSTRY: Network traffic anomaly detection (network operations / ISP / cloud).
APPLICATION: Detecting whether extreme inter-packet gaps cluster in bounded runs.
INCUMBENT: Hurst exponent (RS analysis / DFA), the standard tool for detecting
           long-range dependence in IP traffic.

HYPOTHESIS: The D2 bounded-extremal-clustering statistic detects a specific
structural signature — "extreme gaps never cluster in runs of >=3" — that
the Hurst exponent misses, because Hurst captures *long-range power-law
correlation* but not *local extremal-cluster structure*.

FOUR TRAFFIC REGIMES:
  A. "BCZ-structured" normal traffic: inter-arrival times generated by a
     Farey/BCZ-like rational-grid process. Extreme gaps cluster <=2 (our
     signature). Hurst ~ 0.7 (long-range dependent, similar to B).
  B. "Heavy-tail Poisson" (Pareto inter-arrivals, self-similar): standard
     model for legitimate bursty Internet traffic. Hurst ~ 0.7 also.
     Extreme gaps have unbounded cluster sizes (no BCZ structure).
  C. "DDoS flood" (Poisson with bursty silence): attacker silences create
     long runs of extreme gaps. Cluster sizes >= 5. Hurst ~ 0.5-0.6.
  D. "Pure Poisson" baseline: Exponential inter-arrivals. Cluster sizes
     geometric. Hurst ~ 0.5.

FALSIFICATION TEST: Can D2 (f_ge3 statistic) distinguish A from B,
while Hurst cannot? If Hurst separates A from B → D2 not needed.
If Hurst cannot separate A/B but D2 can → D2 fills a real gap.

We also test whether D2 can distinguish C (attack) from B (legitimate bursty).

VERDICT: Score VALUABLE, APPLICABLE, USABLE, NEEDED based on results.

Run: python3 code/app_wildcard_sim.py
"""

from __future__ import annotations
import math
import numpy as np
import json
import os

rng = np.random.default_rng(20260609)

# ── D2 core: cluster statistics (from d2_diagnostic_suite.py) ────────────────

def normalize_mean1(g: np.ndarray) -> np.ndarray:
    m = g.mean()
    if m <= 0:
        raise ValueError("mean spacing <= 0")
    return g / m


def cluster_stats(gaps: np.ndarray, q: float) -> dict:
    """Cluster statistics on sorted spacings above the q-quantile."""
    thr = np.quantile(gaps, q)
    ext = gaps > thr
    runs = []
    c = 0
    for e in ext:
        if e:
            c += 1
        elif c:
            runs.append(c)
            c = 0
    if c:
        runs.append(c)
    if not runs:
        return dict(nclu=0, maxrun=0, f1=0.0, f2=0.0, fge3=0.0, hist=[0]*5)
    r = np.array(runs, dtype=int)
    nclu = len(r)
    hist = [
        int((r == 1).sum()), int((r == 2).sum()), int((r == 3).sum()),
        int((r == 4).sum()), int((r >= 5).sum()),
    ]
    return dict(
        nclu=nclu, maxrun=int(r.max()),
        f1=float((r == 1).sum() / nclu),
        f2=float((r == 2).sum() / nclu),
        fge3=float((r >= 3).sum() / nclu),
        hist=hist,
    )


def d2_score(gaps: np.ndarray, q: float = 0.95) -> float:
    """D2 anomaly score: f(cluster_size >= 3) at quantile q. Higher = more anomalous."""
    s = cluster_stats(normalize_mean1(gaps), q)
    return s["fge3"]


# ── Hurst exponent (R/S analysis) ─────────────────────────────────────────────

def hurst_rs(x: np.ndarray, min_n: int = 16) -> float:
    """
    Hurst exponent via R/S (rescaled range) analysis.
    Returns H in (0,1); H~0.5 = random walk, H~0.7 = long-range dependent.
    Standard incumbent for network traffic analysis.
    """
    x = np.asarray(x, dtype=float)
    n_total = len(x)
    ns = []
    rs_vals = []
    n = n_total
    while n >= min_n:
        # Split into chunks of size n, compute R/S for each
        n_chunks = n_total // n
        if n_chunks < 1:
            break
        rs_chunk = []
        for i in range(n_chunks):
            seg = x[i*n:(i+1)*n]
            mean_seg = seg.mean()
            dev = np.cumsum(seg - mean_seg)
            R = dev.max() - dev.min()
            S = seg.std(ddof=1)
            if S > 0:
                rs_chunk.append(R / S)
        if rs_chunk:
            ns.append(n)
            rs_vals.append(np.mean(rs_chunk))
        n = n // 2
    if len(ns) < 3:
        return 0.5
    log_n = np.log(ns)
    log_rs = np.log(rs_vals)
    H = np.polyfit(log_n, log_rs, 1)[0]
    return float(np.clip(H, 0.01, 0.99))


# ── Traffic generators ─────────────────────────────────────────────────────────

def farey_gaps(Q: int) -> np.ndarray:
    """Sorted Farey F_Q gaps (number-theoretic spacing structure)."""
    fracs = []
    for q in range(1, Q + 1):
        ps = np.arange(0, q + 1)
        ps = ps[np.gcd(ps, q) == 1]
        fracs.append(ps / q)
    x = np.unique(np.concatenate(fracs))
    return np.diff(x)


def traffic_A_farey_structured(n: int = 50_000) -> np.ndarray:
    """
    Regime A: BCZ/Farey-structured inter-arrival times.
    Method: tile Farey F_500 gaps repeatedly (with small noise) to get n gaps.
    This mimics a network scheduler that operates on a rational-grid timing model
    (e.g., TDMA slots at rational multiples of a base interval).
    Noise added so it's not perfectly periodic (defeats spectral detection).
    """
    base = farey_gaps(500)   # ~76,000 gaps
    # Tile enough to cover n
    tiles = math.ceil(n / len(base)) + 1
    g = np.tile(base, tiles)[:n]
    # Add ~10% white noise so autocorrelation/spectral tests don't trivially work
    noise = rng.uniform(0.0, 0.1 * g.mean(), size=n)
    g = g + noise
    return g.clip(min=1e-9)


def traffic_B_heavy_tail(n: int = 50_000, alpha: float = 1.6) -> np.ndarray:
    """
    Regime B: Pareto (heavy-tail) inter-arrivals — standard self-similar traffic model.
    Hurst ~ 1 - alpha/2 ~ 0.7 for alpha=1.6.
    This is the CAIDA/Paxson Internet traffic model (Poisson is NOT self-similar;
    heavy-tail is the accepted model for legitimate bursty traffic).
    """
    # Pareto with shape alpha, minimum scale 1
    # Mean = alpha/(alpha-1) = 2.67 for alpha=1.6
    u = rng.uniform(0.0, 1.0, size=n)
    g = (1 - u) ** (-1.0 / alpha)   # Pareto CDF inverse: x_min=1, shape=alpha
    return g


def traffic_C_ddos_silence(n: int = 50_000,
                            normal_rate: float = 1.0,
                            attack_prob: float = 0.02,
                            silence_len: int = 8,
                            silence_gap: float = 20.0) -> np.ndarray:
    """
    Regime C: DDoS-style attack with periodic long silences.
    A DDoS flood creates periodic long pauses (attacker's rate limiter, or
    victim's buffer fill). Silences come in bursts of silence_len consecutive
    large gaps, simulating attacker synchronization.
    """
    g = rng.exponential(normal_rate, size=n).astype(float)
    # Inject silence bursts
    i = 0
    while i < n:
        if rng.random() < attack_prob:
            end = min(i + silence_len, n)
            g[i:end] = silence_gap * rng.uniform(0.8, 1.2, size=(end - i))
            i = end + int(rng.exponential(50))
        else:
            i += 1
    return g


def traffic_D_poisson(n: int = 50_000) -> np.ndarray:
    """Regime D: Pure Poisson (Exponential inter-arrivals). Baseline."""
    return rng.exponential(1.0, size=n)


# ── Discrimination experiment ─────────────────────────────────────────────────

def run_experiment(n_trials: int = 30, n_traffic: int = 50_000,
                   q_d2: float = 0.95) -> dict:
    """
    For each regime, run n_trials independent draws, compute:
      - D2 score (f_ge3 at q=0.95)
      - Hurst exponent (R/S)
    Then report mean ± std, and the regime-separation power of each method.

    Key comparison: A vs B (can either method separate them?).
    Secondary: B vs C (attack detection).
    """
    print(f"\nRunning experiment: {n_trials} trials x {n_traffic} gaps each")
    print(f"  D2 quantile q = {q_d2}")

    generators = {
        "A_farey":     lambda: traffic_A_farey_structured(n_traffic),
        "B_heavy_tail": lambda: traffic_B_heavy_tail(n_traffic),
        "C_ddos":      lambda: traffic_C_ddos_silence(n_traffic),
        "D_poisson":   lambda: traffic_D_poisson(n_traffic),
    }

    results = {}
    for name, gen in generators.items():
        d2_scores = []
        h_scores = []
        print(f"  {name}...", end="", flush=True)
        for t in range(n_trials):
            g = gen()
            d2 = d2_score(g, q=q_d2)
            h = hurst_rs(g)
            d2_scores.append(d2)
            h_scores.append(h)
            if (t + 1) % 10 == 0:
                print(".", end="", flush=True)
        print()
        results[name] = {
            "d2_mean": float(np.mean(d2_scores)),
            "d2_std":  float(np.std(d2_scores)),
            "d2_vals": d2_scores,
            "h_mean":  float(np.mean(h_scores)),
            "h_std":   float(np.std(h_scores)),
            "h_vals":  h_scores,
        }

    return results


def separation_power(vals_a: list, vals_b: list) -> dict:
    """
    Compute separation power between two distributions using:
      1. Effect size (Cohen's d): |mu_a - mu_b| / pooled_std
      2. AUROC (probability D2(B) > D2(A) that a random B-draw > random A-draw)
    """
    a = np.array(vals_a)
    b = np.array(vals_b)
    pooled_std = math.sqrt((a.var(ddof=1) + b.var(ddof=1)) / 2)
    if pooled_std < 1e-12:
        cohen_d = 0.0
    else:
        cohen_d = abs(a.mean() - b.mean()) / pooled_std

    # AUROC via counting (Monte Carlo)
    n_mc = 10_000
    ia = rng.integers(0, len(a), size=n_mc)
    ib = rng.integers(0, len(b), size=n_mc)
    # AUROC = P(score_B > score_A) when B is the "anomalous" class
    auroc = float((b[ib] > a[ia]).mean())

    return {"cohen_d": float(cohen_d), "auroc": float(auroc)}


def main():
    print("=" * 72)
    print("CANDIDATE 3 WILDCARD: Network Traffic Anomaly Detection")
    print("Industry: Network operations (ISP / cloud / enterprise NOC)")
    print("Incumbent: Hurst exponent (R/S analysis)")
    print("Our method: D2 bounded-extremal-clustering (f_ge3 at q=0.95)")
    print("=" * 72)

    print("""
FOUR REGIMES:
  A. Farey/BCZ-structured traffic (rational-grid scheduler, cluster<=2)
  B. Heavy-tail Pareto (self-similar, Paxson model, cluster unbounded)
  C. DDoS-silence attack (long-run silence bursts, cluster>=5)
  D. Pure Poisson baseline (Exp inter-arrivals)

KEY QUESTION: Can D2 separate A from B when Hurst cannot?
If Hurst H(A) ≈ H(B) but D2(A) << D2(B) → D2 fills a gap.
If Hurst already separates A/B → D2 is not needed.
""")

    # Run main experiment
    results = run_experiment(n_trials=30, n_traffic=50_000, q_d2=0.95)

    print("\n" + "=" * 72)
    print("RESULTS: Mean ± std per regime")
    print("=" * 72)
    print(f"  {'Regime':<18s}  {'D2 f_ge3':>12s}  {'Hurst H':>12s}")
    print(f"  {'-'*18}  {'-'*12}  {'-'*12}")
    labels = {
        "A_farey":      "A: Farey/BCZ",
        "B_heavy_tail": "B: Heavy-tail",
        "C_ddos":       "C: DDoS-silence",
        "D_poisson":    "D: Poisson",
    }
    for key, label in labels.items():
        r = results[key]
        print(f"  {label:<18s}  {r['d2_mean']:6.4f} ± {r['d2_std']:.4f}  "
              f"  {r['h_mean']:6.4f} ± {r['h_std']:.4f}")

    # ── Separation analysis ────────────────────────────────────────────────────
    print("\n" + "=" * 72)
    print("SEPARATION POWER: Cohen's d and AUROC (B as 'anomalous' vs A)")
    print("=" * 72)

    pairs = [
        ("A vs B", "A_farey", "B_heavy_tail",
         "Can we tell Farey from heavy-tail? (Hurst can't if H_A ≈ H_B)"),
        ("A vs C", "A_farey", "C_ddos",
         "Farey vs DDoS-attack (attack detection)"),
        ("B vs C", "B_heavy_tail", "C_ddos",
         "Heavy-tail vs DDoS (attack within bursty traffic)"),
        ("A vs D", "A_farey", "D_poisson",
         "Farey vs Poisson (basic sanity check)"),
    ]

    pair_results = {}
    for label, ka, kb, desc in pairs:
        d2_sep = separation_power(results[ka]["d2_vals"], results[kb]["d2_vals"])
        h_sep  = separation_power(results[ka]["h_vals"],  results[kb]["h_vals"])
        print(f"\n  {label}: {desc}")
        print(f"    D2  Cohen_d={d2_sep['cohen_d']:6.3f}  AUROC={d2_sep['auroc']:.3f}")
        print(f"    Hurst Cohen_d={h_sep['cohen_d']:6.3f}  AUROC={h_sep['auroc']:.3f}")
        winner = "D2" if d2_sep["auroc"] > h_sep["auroc"] else "Hurst"
        print(f"    Winner: {winner}")
        pair_results[label] = {"d2": d2_sep, "h": h_sep, "winner": winner}

    # ── Detailed breakdown at q=0.95 ──────────────────────────────────────────
    print("\n" + "=" * 72)
    print("DETAILED D2 CLUSTER BREAKDOWN (one representative draw per regime)")
    print("=" * 72)
    qs = [0.90, 0.95, 0.99]
    gen_map = {
        "A: Farey/BCZ":     traffic_A_farey_structured,
        "B: Heavy-tail":    traffic_B_heavy_tail,
        "C: DDoS-silence":  traffic_C_ddos_silence,
        "D: Poisson":       traffic_D_poisson,
    }
    for label, gen in gen_map.items():
        g = gen(50_000)
        gn = normalize_mean1(g)
        print(f"\n  {label}")
        for q in qs:
            s = cluster_stats(gn, q)
            print(f"    q={q:.2f}: maxrun={s['maxrun']:3d}  f1={s['f1']:.3f}  "
                  f"f2={s['f2']:.3f}  f_ge3={s['fge3']:.4f}  "
                  f"hist={s['hist']}")

    # ── Critical analysis: the real gap ───────────────────────────────────────
    print("\n" + "=" * 72)
    print("CRITICAL ANALYSIS: Does D2 fill a real gap the incumbent misses?")
    print("=" * 72)

    a_h = results["A_farey"]["h_mean"]
    b_h = results["B_heavy_tail"]["h_mean"]
    a_d2 = results["A_farey"]["d2_mean"]
    b_d2 = results["B_heavy_tail"]["d2_mean"]

    h_overlap = abs(a_h - b_h) < 1.5 * (results["A_farey"]["h_std"] + results["B_heavy_tail"]["h_std"])
    d2_separates = (b_d2 - a_d2) > 3 * max(results["A_farey"]["d2_std"],
                                             results["B_heavy_tail"]["d2_std"])

    print(f"\n  Hurst: H(A)={a_h:.4f}, H(B)={b_h:.4f}  "
          f"=> overlap={'YES (cannot separate)' if h_overlap else 'NO (can separate)'}")
    print(f"  D2:    f_ge3(A)={a_d2:.4f}, f_ge3(B)={b_d2:.4f}  "
          f"=> separates={'YES (>3sigma gap)' if d2_separates else 'NO'}")

    gap_filled = h_overlap and d2_separates
    print(f"\n  Gap filled by D2 (Hurst blind, D2 sees it): {gap_filled}")

    # ── Verdict ───────────────────────────────────────────────────────────────
    print("\n" + "=" * 72)
    print("SCORING")
    print("=" * 72)

    # Compute AUROC for A vs B with D2 and Hurst
    avb_d2 = pair_results["A vs B"]["d2"]["auroc"]
    avb_h  = pair_results["A vs B"]["h"]["auroc"]

    print(f"""
  VALUABLE  (who pays?):
    Network ops teams (ISPs, cloud NOCs) pay for traffic classification and
    anomaly detection tools. Market exists: Cloudflare, AWS, enterprise SIEM.
    BUT: the use case (detecting Farey-structured traffic from heavy-tail) is
    extremely niche — real Farey-structured schedulers are rare in practice.
    Verdict: LOW-MODERATE. Real money exists in anomaly detection, but our
    specific structural signature is not present in typical real traffic.

  APPLICABLE (does our method apply to real data?):
    Real packet inter-arrivals: Pareto/heavy-tail (Paxson 1995, CAIDA).
    Farey-structured schedulers: exist in TDMA/WiMAX with rational slot grids,
    industrial IoT with deterministic schedulers. NICHE but real.
    D2 needs a sorted spacing sequence — applies directly to sorted
    inter-arrival times (like Farey gaps = sorted rational fractions).
    Verdict: MODEST. Applies to a specific class of schedulers, not generic.

  USABLE    (deployable simply?):
    D2 is O(n log n) (sort + scan). No model fitting, no parameter tuning
    beyond quantile q. Single number output (f_ge3).
    BUT: the method's interpretation requires knowing q* = 0.862, which
    is BCZ-specific. For network data the threshold is empirical.
    Verdict: MODERATE-MODEST. Simple to compute, but calibration unclear.

  NEEDED    (real gap incumbents leave?):
    Hurst AUROC(A vs B) = {avb_h:.3f} vs D2 AUROC(A vs B) = {avb_d2:.3f}.
    Gap filled: {gap_filled}.
    If D2 AUROC >> Hurst AUROC → real gap. If similar → no gap.
    Verdict: depends on numbers above.
""")

    # Final fit assessment
    edge_demonstrated = gap_filled and (avb_d2 - avb_h > 0.05)
    print(f"  edge_demonstrated = {edge_demonstrated}")
    print(f"  gap_filled        = {gap_filled}")
    print(f"  D2 AUROC(A vs B)  = {avb_d2:.3f}")
    print(f"  Hurst AUROC(A vs B) = {avb_h:.3f}")

    # ── Save results ──────────────────────────────────────────────────────────
    out_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "out")
    os.makedirs(out_dir, exist_ok=True)
    out = {
        "experiment": "app_wildcard_sim",
        "industry": "Network traffic anomaly detection",
        "incumbent": "Hurst exponent (R/S analysis)",
        "our_method": "D2 bounded-extremal-clustering (f_ge3)",
        "n_trials": 30,
        "n_traffic": 50_000,
        "q_d2": 0.95,
        "regime_results": {
            k: {"d2_mean": v["d2_mean"], "d2_std": v["d2_std"],
                "h_mean": v["h_mean"], "h_std": v["h_std"]}
            for k, v in results.items()
        },
        "pair_separation": pair_results,
        "gap_filled": gap_filled,
        "edge_demonstrated": edge_demonstrated,
        "A_vs_B": {
            "d2_auroc": avb_d2,
            "h_auroc": avb_h,
            "d2_wins": avb_d2 > avb_h,
        },
    }
    out_path = os.path.join(out_dir, "app_wildcard_results.json")
    with open(out_path, "w") as f:
        json.dump(out, f, indent=2)
    print(f"\nResults saved to {out_path}")
    return out


if __name__ == "__main__":
    main()
