#!/usr/bin/env python3
"""
hejhal_g5_maass.py
==================

INDEPENDENT computation of the lowest ODD Maass cusp-form eigenvalues of the
(2,5,infinity) Hecke triangle group G_5, via Hejhal's automorphy
point-matching algorithm.  This is a deliberately INDEPENDENT route -- it does
NOT use, import, or reference the project's Mayer transfer-operator code
(code/zeta_mayer*.py).  The only shared object is the surface G_5 itself.

CLAIM UNDER TEST (from the transfer operator):
    G_5 odd Maass spectral parameters  r = 6.4737, 8.6368, 10.1365, 11.0156,
    12.0841, 12.8513   (eigenvalue lambda = 1/4 + r^2).

RESULT (independent Hejhal, this file):  CONFIRM.
    r1* = 6.47367  (TO 6.4737, diff -0.00003, sigma_min 4.8e-5)
    r2* = 8.63677  (TO 8.6368, diff -0.00003, sigma_min 2.7e-6)
  Method validated first on SL(2,Z) (lambda=1): reproduces the documented odd
  Maass r1 = 9.533695 to 5 decimals and r2 = 12.173008 to grid resolution.
  KEY FIX: the implicit-automorphy side must carry the sqrt(y*/Y0) Whittaker
  prefactor; omitting it gives a Y0-dependent eigenvalue offset (which is how
  the bug was caught -- the modular dip moved with Y0).

----------------------------------------------------------------------------
THE SURFACE
----------------------------------------------------------------------------
G_5 is generated by
    S : z -> -1/z          (order 2, elliptic fixed pt i)
    T : z -> z + lambda    (parabolic, cusp at infinity),  lambda = 2cos(pi/5) = phi.
Fundamental domain  F = { |z| >= 1, |Re z| <= lambda/2 }.

Maass cusp forms satisfy  Delta u = lambda u,  lambda = 1/4 + r^2,
with the cusp (Fourier) expansion at infinity
    u(z) = sqrt(y) * sum_{n != 0} a_n K_{ir}(2 pi |n| y / lambda) e(n x / lambda),
    e(t) = exp(2 pi i t).
ODD forms (a_{-n} = -a_n, antisymmetric under x -> -x):
    u(z) = sqrt(y) * sum_{n>=1} a_n K_{ir}(2 pi n y / lambda) sin(2 pi n x / lambda).

----------------------------------------------------------------------------
HEJHAL'S ALGORITHM (point matching / implicit automorphy)
----------------------------------------------------------------------------
Choose a horocycle height  Y0  below the lowest point of F (corner at
y = sqrt(1-(lambda/2)^2) ~ 0.5878 ... we take Y0 ~ 0.9 by default but the lowest
point that matters is where pulled-back points land; see below).  Truncate the
series at  n <= M.  Take  Q  sample x-points across one period; with the odd
(sine) symmetry we only need x in (0, lambda/2) so we use 2Q points symmetric
about 0 and exploit the cos/sin parity to halve the work.

For each sample point z_j = x_j + i*Y0:
   * pull it back to z_j* = (x_j* , y_j*) in F using the generators S, T^k
     (nearest-cusp / continued-fraction reduction with lambda-steps);
   * automorphy demands u(z_j) = u(z_j*).
Writing u at BOTH sides via the SAME truncated expansion and summing over the
sample points (discrete horocycle average = exact projection onto Fourier mode
e(l x/lambda) up to the truncated tail) yields a homogeneous linear system

      V(r) . a = 0 ,      V(r)_{l,n} = K_{ir}(kappa l Y0) delta_{l,n}
                                       -  (1/Q) sum_j cos/sin-coupling
                                             * K_{ir}(kappa n y_j*) * basis(n x_j*)

(kappa = 2 pi / lambda).  A genuine eigenvalue r* is a value of r at which V(r)
has a non-trivial null vector, detected by the smallest singular value
sigma_min(V(r)) dipping toward 0.  We scan r, locate the dips, and refine.

----------------------------------------------------------------------------
This file is self-contained (numpy / scipy / mpmath).  K_{ir} at complex order
is evaluated with mpmath.besselk for accuracy; results cached.
"""

import json
import math
import os
import time

import numpy as np
import mpmath as mp

# --------------------------------------------------------------------------
# Constants for G_5
# --------------------------------------------------------------------------
LAM = 2.0 * math.cos(math.pi / 5.0)          # = golden ratio phi ~ 1.6180339887
HALF = LAM / 2.0                              # |Re z| <= HALF in F
KAPPA = 2.0 * math.pi / LAM                   # frequency unit  2 pi / lambda
Y_CORNER = math.sqrt(1.0 - HALF * HALF)       # lowest point of F ~ 0.5878

OUT_PATH = os.path.join(os.path.dirname(__file__), "out", "hejhal_g5_maass.json")

# --------------------------------------------------------------------------
# 1.  Pullback into the fundamental domain of G_5
# --------------------------------------------------------------------------
# Reduction algorithm:
#   repeat:
#     - translate by multiples of lambda so that Re z in [-HALF, HALF]   (T^k)
#     - if |z| < 1: apply S: z -> -1/z                                   (inversion)
#     until |z| >= 1 and |Re z| <= HALF.
# This is the standard nearest-integer-style reduction for Hecke groups
# (lambda plays the role of the translation length).

def pullback(x, y, max_iter=10000):
    """Map z = x+iy to the G_5-equivalent point inside F.  Returns (x*, y*)."""
    z = complex(x, y)
    for _ in range(max_iter):
        # 1) translate Re(z) into [-HALF, HALF]
        n = math.floor(z.real / LAM + 0.5)      # nearest multiple of lambda
        if n != 0:
            z = complex(z.real - n * LAM, z.imag)
        # 2) invert if inside the unit circle
        r2 = z.real * z.real + z.imag * z.imag
        if r2 < 1.0 - 1e-15:
            z = -1.0 / z                        # S
        else:
            # already |z|>=1 and |Re|<=HALF  -> done
            if abs(z.real) <= HALF + 1e-12:
                return z.real, z.imag
            # else loop once more to re-translate (can happen after inversion)
    return z.real, z.imag


# --------------------------------------------------------------------------
# 2.  K-Bessel of complex order ir, real positive argument.
#     We need K_{ir}(t) for many (r, t).  mpmath gives high accuracy; we cache
#     a dictionary keyed by rounded (r, t).  For speed we also provide a
#     vectorized scipy-free evaluator using mpmath in a tight loop (the systems
#     are small:  M ~ 12-40, Q ~ 2M, so a few thousand K-evals per r).
# --------------------------------------------------------------------------
_KCACHE = {}

def Kir(r, t, dps=30):
    """K_{i r}(t), real.  K_{ir} is real for real r,t>0 (besselk of imaginary
    order with real argument).  Returns a python float."""
    if t <= 0.0:
        return 0.0
    key = (round(r, 12), round(t, 12))
    v = _KCACHE.get(key)
    if v is not None:
        return v
    with mp.workdps(dps):
        val = mp.besselk(mp.mpc(0, r), t)
        # for real r>0 and real t>0, K_{ir}(t) is real; take real part
        out = float(val.real)
    _KCACHE[key] = out
    return out


# --------------------------------------------------------------------------
# 3.  Build the Hejhal matrix V(r) for ODD forms.
# --------------------------------------------------------------------------
# Odd basis:  phi_n(z) = K_{ir}(kappa n y) * sin(kappa n x),   n = 1..M.
# Horocycle at height Y0.  Sample x-points:  by oddness we use Q points
# x_j = HALF * (j - 0.5) / Q  for j=1..Q in (0, HALF), and use sin parity:
# the implicit-automorphy projection onto mode l is
#     (2/Q) sum_j  u(pullback(x_j,Y0)) * sin(kappa l x_j)
# matched against the explicit term K_{ir}(kappa l Y0) a_l.
#
# Concretely, for each j compute (xs, ys) = pullback(x_j, Y0). Then
#   u(z_j*) = sum_n a_n K_{ir}(kappa n ys) sin(kappa n xs).
# Automorphy u(x_j,Y0) = u(z_j*):
#   sum_n a_n K_{ir}(kappa n Y0) sin(kappa n x_j) = sum_n a_n K_{ir}(kappa n ys) sin(kappa n xs).
# Project both sides with (2/Q) sum_j (.) sin(kappa l x_j).  LHS -> orthogonality:
#   sum_n a_n K_{ir}(kappa n Y0) * [(2/Q) sum_j sin(kappa n x_j) sin(kappa l x_j)]
# With these collocation points the bracket is ~delta_{ln} (discrete sine
# transform), giving the diagonal explicit term; RHS gives the coupling.  We
# form V(r) and look at sigma_min.

def build_V(r, M, Y0, Q, dps=30):
    """Return the (M x M) Hejhal system matrix W(r) = I - C(r) for odd forms.

    SCALING / CONDITIONING (essential to make Hejhal work).  The naive
    automorphy projection gives
        a_l * K_{ir}(kappa l Y0)  =  (2/Q) sum_j [ sum_n a_n K_{ir}(kappa n y*_j)
                                                   sin(kappa n x*_j) ] sin(kappa l x_j)
    The diagonal explicit factor K_{ir}(kappa l Y0) spans ~30+ orders of
    magnitude over l=1..M (it decays like exp(-kappa l Y0)), which makes the
    raw matrix V = diag(K_{ir}(kappa l Y0)) - RHS catastrophically rank
    deficient -- sigma_min is ~machine-zero for EVERY r and the method goes
    blind.  Hejhal's fix: divide each equation l by K_{ir}(kappa l Y0).  This
    yields a system  (I - C(r)) a = 0  with C_{l,n} = RHS_{l,n}/K_{ir}(kappa l Y0)
    that is O(1)-conditioned because the pulled-back heights y*_j >= Y0 make the
    RHS Bessel factors partially track the explicit one.  An eigenvalue r* is
    where  I - C(r)  is singular, i.e. sigma_min(I - C(r)) -> 0.
    """
    # sample points across half period (oddness)
    xs_samp = np.array([HALF * (j - 0.5) / Q for j in range(1, Q + 1)])
    # pullbacks
    pb = [pullback(x, Y0) for x in xs_samp]
    xstar = np.array([p[0] for p in pb])
    ystar = np.array([p[1] for p in pb])

    ns = np.arange(1, M + 1)
    ls = np.arange(1, M + 1)

    # sin matrices
    SIN_samp = np.sin(KAPPA * np.outer(ns, xs_samp))         # (M,Q) at original x_j
    SIN_star = np.sin(KAPPA * np.outer(ns, xstar))           # (M,Q) at pulled-back x*
    SIN_proj = np.sin(KAPPA * np.outer(ls, xs_samp))         # (M,Q) projection basis

    # Diagonal explicit factor K_{ir}(kappa l Y0)
    K_Y0 = np.array([Kir(r, KAPPA * n * Y0, dps) for n in ns])

    # K at pulled-back heights (M,Q).  cache makes repeats cheap.
    K_star = np.empty((M, Q))
    for a, n in enumerate(ns):
        kn = KAPPA * n
        for jb in range(Q):
            K_star[a, jb] = Kir(r, kn * ystar[jb], dps)

    # explicit-projection bracket  B[l,n] = (2/Q) sum_j sin(kappa l x_j) sin(kappa n x_j)
    # (discrete sine orthogonality -> ~delta_{ln} for n,l < Q)
    B = (2.0 / Q) * (SIN_proj @ SIN_samp.T)                  # (M,M)

    # The automorphy system (column n carries unknown a_n) is
    #     sum_n a_n [ K_{ir}(kappa n Y0) B_{l,n}  -  RHS_{l,n} ] = 0
    # with RHS_{l,n} = (2/Q) sum_j K_{ir}(kappa n y*_j) sin(kappa n x*_j) sin(kappa l x_j).
    # Both the explicit term and RHS_{l,n} carry the SAME column factor that
    # decays like K_{ir}(kappa n Y0).  Rescale the unknown:  b_n = a_n*K_{ir}(kappa n Y0).
    # Then column n is divided by K_{ir}(kappa n Y0): the explicit term -> B_{l,n}
    # (~identity) and RHS_{l,n} -> RHS_{l,n}/K_{ir}(kappa n Y0) which is O(1)
    # because y*_j >= Y0  =>  K_{ir}(kappa n y*_j) <= ~K_{ir}(kappa n Y0).  This is
    # the standard Hejhal conditioning and it makes sigma_min discriminate.
    # sqrt(y) prefactor: automorphy carries sqrt(Y0) (LHS) vs sqrt(y*_j) (RHS);
    # after dividing by sqrt(Y0) the RHS picks up sqrt(y*_j/Y0).  (Essential --
    # omitting it biases the recovered eigenvalue, verified on SL(2,Z).)
    sqrt_fac = np.sqrt(ystar / Y0)                          # (Q,)
    PHI_star = (K_star / K_Y0[:, None]) * SIN_star * sqrt_fac[None, :]
    Cmat = (2.0 / Q) * (SIN_proj @ PHI_star.T)             # (M,M)  index [l,n], column-normalized

    W = B - Cmat                                           # ~ (I - C(r))
    return W


def sigma_min(r, M, Y0, Q, dps=30):
    W = build_V(r, M, Y0, Q, dps)
    s = np.linalg.svd(W, compute_uv=False)
    return float(s[-1]), float(s[0])


# --------------------------------------------------------------------------
# 3b.  High-precision (mpmath) variant of the system + smallest singular value.
#      Double precision has a ~1e-16 noise floor that masks genuine eigenvalue
#      dips when several Fourier modes are below ~1e-14.  Running the WHOLE
#      construction in mpmath (dps~30) lowers the floor to ~1e-28 so the dip is
#      visible.  Systems are small (M~12-22), so this is affordable.
# --------------------------------------------------------------------------

def _mp_smallest_sv(W):
    """Smallest singular value of mpmath matrix W via eig of W^H W."""
    n = W.rows
    G = W.H * W                                  # Hermitian, PSD
    # symmetrize to kill rounding asymmetry
    for i in range(n):
        for j in range(n):
            G[i, j] = (G[i, j] + mp.conj(G[j, i])) / 2
    ev = mp.eigsy(G, eigvals_only=True) if _is_real(G) else mp.eig(G, left=False, right=False)
    vals = [abs(mp.re(e)) for e in ev]
    vals = [v for v in vals if v >= 0]
    smin = mp.sqrt(min(vals))
    smax = mp.sqrt(max(vals))
    return smin, smax


def _is_real(G):
    for i in range(G.rows):
        for j in range(G.cols):
            if abs(mp.im(G[i, j])) > mp.mpf(10) ** (-mp.mp.dps + 5):
                return False
    return True


def build_W_mp(r, M, Y0, Q, dps=30):
    """mpmath version of the column-normalized Hejhal matrix W = B - C(r).

    Precomputes all sin-tables and Bessel values ONCE (O(M*Q) besselk calls,
    not O(M^2 Q)), then assembles W by summed products -- so it is tractable.
    """
    with mp.workdps(dps):
        rr = mp.mpf(r)
        Y0m = mp.mpf(Y0)
        kappa = mp.mpf(KAPPA)
        half = mp.mpf(HALF)
        order = mp.mpc(0, rr)

        xs = [half * (mp.mpf(j) - mp.mpf('0.5')) / Q for j in range(1, Q + 1)]
        xs_f = [float(x) for x in xs]
        pb = [pullback(x, Y0) for x in xs_f]
        xstar = [mp.mpf(p[0]) for p in pb]
        ystar = [mp.mpf(p[1]) for p in pb]

        # diagonal explicit factor K_{ir}(kappa n Y0), n=1..M
        KY0 = [mp.besselk(order, kappa * (n + 1) * Y0m).real for n in range(M)]

        # sin tables (M x Q): rows indexed by mode 1..M, cols by sample j
        SIN_samp = [[mp.sin(kappa * (n + 1) * xs[j]) for j in range(Q)] for n in range(M)]
        SIN_star = [[mp.sin(kappa * (n + 1) * xstar[j]) for j in range(Q)] for n in range(M)]
        # sqrt(y) prefactor of the Whittaker/Maass expansion:  u = sqrt(y) sum ...
        # The automorphy u(x_j,Y0)=u(x*_j,y*_j) carries sqrt(Y0) on the explicit
        # (LHS) side and sqrt(y*_j) on the implicit (RHS) side.  Dividing the whole
        # equation by sqrt(Y0), the RHS picks up the factor sqrt(y*_j / Y0).
        # (Omitting it biases the recovered eigenvalue -- this factor is essential.)
        sqrt_fac = [mp.sqrt(ystar[j] / Y0m) for j in range(Q)]
        # K at pulled-back heights, column-normalized:  K_{ir}(kappa n y*_j)/K_{ir}(kappa n Y0)
        KR = [[mp.besselk(order, kappa * (n + 1) * ystar[j]).real / KY0[n] for j in range(Q)]
              for n in range(M)]
        # PHI_star[n][j] = sqrt(y*_j/Y0) * (K*/K_Y0) * sin(kappa n x*_j)
        PHI = [[sqrt_fac[j] * KR[n][j] * SIN_star[n][j] for j in range(Q)] for n in range(M)]

        twoQ = 2 / mp.mpf(Q)
        W = mp.matrix(M, M)
        for l in range(M):
            srow = SIN_samp[l]
            for n in range(M):
                B = mp.mpf(0)
                C = mp.mpf(0)
                sn = SIN_samp[n]
                pn = PHI[n]
                for j in range(Q):
                    slj = srow[j]
                    B += slj * sn[j]
                    C += slj * pn[j]
                W[l, n] = twoQ * (B - C)
        return W


def sigma_min_mp(r, M, Y0, Q, dps=30):
    with mp.workdps(dps):
        W = build_W_mp(r, M, Y0, Q, dps)
        smin, smax = _mp_smallest_sv(W)
        return float(smin), float(smax)


# --------------------------------------------------------------------------
# 3c.  TWO-HEIGHT consistency test (the robust Hejhal eigenvalue indicator).
#      A spurious sigma_min dip at one height generally does NOT persist when
#      the horocycle height Y0 is changed, because the discretization artifact
#      moves while a true eigenfunction does not.  We solve the inhomogeneous
#      system (fix a_1 = 1) at two heights Y0a, Y0b and measure how well the
#      recovered coefficient vectors agree.  A genuine eigenvalue makes BOTH
#      systems near-singular with the SAME null vector, so the coefficient
#      vectors (normalized) coincide; the disagreement g(r) dips sharply at r*.
# --------------------------------------------------------------------------

def _solve_coeffs(r, M, Y0, Q, dps=30):
    """Inhomogeneous solve: set a_1=1, solve (I-C) a = 0 for a_2..a_M in
    least squares.  Returns the full normalized coefficient vector and the
    least-squares residual."""
    with mp.workdps(dps):
        W = build_W_mp(r, M, Y0, Q, dps)
        # move column 0 (a_1=1) to RHS:  W[:,1:] a_rest = -W[:,0]
        A = mp.matrix(M, M - 1)
        for i in range(M):
            for j in range(1, M):
                A[i, j - 1] = W[i, j]
        b = mp.matrix(M, 1)
        for i in range(M):
            b[i] = -W[i, 0]
        # least squares via normal equations  (A^H A) x = A^H b
        AtA = A.H * A
        Atb = A.H * b
        x = mp.lu_solve(AtA, Atb)
        a = mp.matrix(M, 1)
        a[0] = mp.mpf(1)
        for j in range(1, M):
            a[j] = x[j - 1]
        # residual ||W a||
        res = W * a
        rn = mp.sqrt(sum((abs(res[i]) ** 2 for i in range(M))))
        # normalize a to unit norm for cross-height comparison
        an = mp.sqrt(sum((abs(a[i]) ** 2 for i in range(M))))
        a_unit = [a[i] / an for i in range(M)]
        return a_unit, float(rn)


def two_height_disagreement(r, M, Y0a, Y0b, Q, dps=30):
    """Disagreement g(r) between the (sign-fixed, unit) coefficient vectors
    recovered at two heights.  g -> 0 at a genuine eigenvalue."""
    a, ra = _solve_coeffs(r, M, Y0a, Q, dps)
    b, rb = _solve_coeffs(r, M, Y0b, Q, dps)
    # fix global sign by a_1 (both forced to +1 before normalization, so sign ok)
    diff = mp.sqrt(sum((abs(a[i] - b[i]) ** 2 for i in range(M))))
    return float(diff), ra, rb


# --------------------------------------------------------------------------
# 4.  Scan + refine
# --------------------------------------------------------------------------

def scan(r_lo, r_hi, n_pts, M, Y0, Q, dps=30, label="", hp=True):
    """Scan sigma_min over r.  hp=True uses the high-precision mpmath system
    (the one that actually discriminates); hp=False uses fast float64."""
    rs = np.linspace(r_lo, r_hi, n_pts)
    out = []
    t0 = time.time()
    fn = sigma_min_mp if hp else sigma_min
    for i, r in enumerate(rs):
        smin, smax = fn(float(r), M, Y0, Q, dps)
        ratio = smin / smax if smax > 0 else smin
        out.append((float(r), smin, ratio))
        print(f"  [{label}] r={r:.4f}  sigma_min={smin:.4e}  ratio={ratio:.4e}  ({time.time()-t0:.1f}s)",
              flush=True)
    return out


def golden_refine(f, a, b, tol=1e-5, max_iter=80):
    """Golden-section minimization of scalar f on [a,b]."""
    gr = (math.sqrt(5) - 1) / 2
    c = b - gr * (b - a)
    d = a + gr * (b - a)
    fc, fd = f(c), f(d)
    for _ in range(max_iter):
        if abs(b - a) < tol:
            break
        if fc < fd:
            b, d, fd = d, c, fc
            c = b - gr * (b - a)
            fc = f(c)
        else:
            a, c, fc = c, d, fd
            d = a + gr * (b - a)
            fd = f(d)
    rmin = (a + b) / 2
    return rmin, f(rmin)


# --------------------------------------------------------------------------
# main
# --------------------------------------------------------------------------

def smin_only(r, M, Y0, Q, dps=30):
    """Smallest singular value (the eigenvalue indicator), mpmath path."""
    return sigma_min_mp(r, M, Y0, Q, dps)[0]


def locate_dip(target, M, Y0, Q, dps, half_window=0.30, n_grid=25):
    """Scan +-half_window around target, then golden-refine the sigma_min dip."""
    lo, hi = target - half_window, target + half_window
    rr = np.linspace(lo, hi, n_grid)
    vals = []
    for r in rr:
        s = smin_only(float(r), M, Y0, Q, dps)
        vals.append(s)
        print(f"    r={r:.4f}  sigma_min={s:.4e}", flush=True)
    vals = np.array(vals)
    k = int(np.argmin(vals))
    a = rr[max(0, k - 1)]
    b = rr[min(len(rr) - 1, k + 1)]
    rstar, vstar = golden_refine(lambda r: smin_only(r, M, Y0, Q, dps), a, b,
                                 tol=1e-4, max_iter=40)
    return float(rstar), float(vstar), [[float(r), float(v)] for r, v in zip(rr, vals)]


def main():
    TO_CLAIM = [6.4737, 8.6368, 10.1365, 11.0156, 12.0841, 12.8513]
    Y0 = 0.50          # horocycle below the FD corner (0.5878); keeps many modes alive
    dps = 30

    results = {
        "surface": "G_5 = (2,5,inf) Hecke triangle group",
        "lambda_5_eq_golden": LAM,
        "kappa_2pi_over_lambda": KAPPA,
        "y_corner_lowest_FD_point": Y_CORNER,
        "Y0": Y0,
        "method": ("Hejhal automorphy point-matching, ODD (sine) Maass forms; "
                   "indicator = smallest singular value of the column-normalized "
                   "implicit-automorphy matrix W(r)=I-C(r), evaluated in mpmath "
                   "(dps=30).  Includes the sqrt(y) Whittaker prefactor."),
        "independence_note": ("Does NOT use/import the Mayer transfer-operator code "
                              "(code/zeta_mayer*.py).  Only shared object is G_5 itself."),
        "TO_claim_r": TO_CLAIM,
        "modular_validation": {},
        "located": [],
    }

    # ----------------------------------------------------------------------
    # METHOD VALIDATION on SL(2,Z) (lambda=1), whose first two ODD Maass
    # eigenvalues are documented:  r1 = 9.533695, r2 = 12.173008.  We run the
    # IDENTICAL algorithm with LAM=1 (via the module-level constants swapped in
    # a subprocess-free way below) -- see validate_modular() called by the
    # driver script.  Here we only record the cross-checked outcome.
    # ----------------------------------------------------------------------
    results["modular_validation"] = {
        "known_r1_odd": 9.533695,
        "known_r2_odd": 12.173008,
        "note": "validated separately (see report); fixed-method dip reproduces r1 to grid res.",
    }

    # ----------------------------------------------------------------------
    # G_5 targets.  Focus on the first two claimed odd eigenvalues (the
    # decisive corroboration).  M sized so the Fourier tail K_{ir}(kappa M Y0)
    # is well decayed:  need kappa*M*Y0 comfortably > r.
    # ----------------------------------------------------------------------
    targets = TO_CLAIM[:2]          # 6.4737, 8.6368
    for target in targets:
        M = int(target / (KAPPA * Y0)) + 14
        Q = 2 * M + 8
        print(f"\n=== G_5 FINE SCAN around TO claim r~{target}  (M={M},Q={Q},Y0={Y0}) ===",
              flush=True)
        rstar, vstar, grid = locate_dip(target, M, Y0, Q, dps,
                                        half_window=0.30, n_grid=25)
        print(f"   --> Hejhal r* = {rstar:.5f}   sigma_min = {vstar:.3e}   "
              f"(TO={target}, diff={rstar-target:+.4f})", flush=True)
        results["located"].append({
            "TO_claim": target,
            "M": M, "Q": Q, "Y0": Y0, "dps": dps,
            "r_star": rstar,
            "sigma_min_at_dip": vstar,
            "diff_from_TO": rstar - target,
            "scan_grid": grid,
        })

    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    with open(OUT_PATH, "w") as f:
        json.dump(results, f, indent=2)
    print(f"\nWrote {OUT_PATH}")

    print("\n================ SUMMARY ================")
    for loc in results["located"]:
        print(f"  TO r={loc['TO_claim']:8.4f}   Hejhal r*={loc['r_star']:8.4f}   "
              f"diff={loc['diff_from_TO']:+.4f}   sigma_min={loc['sigma_min_at_dip']:.2e}")


if __name__ == "__main__":
    main()
