#!/usr/bin/env python3
"""
hejhal_g8_maass.py
==================

INDEPENDENT confirmation of the lowest ODD Maass cusp-form spectral parameters
of the (2,8,infinity) Hecke triangle group G_8, via Hejhal's automorphy
point-matching algorithm.  This is the SECOND non-arithmetic surface validated
this way (after G_5 in hejhal_g8_maass.py's sibling hejhal_g5_maass.py) and is
deliberately INDEPENDENT of the project's Mayer transfer-operator code
(code/zeta_mayer*.py).  The only shared object is the surface itself.

It REUSES the validated G_5 machinery verbatim (pullback / nearest-lambda
reduction + S-inversion, column-normalized implicit-automorphy matrix, sqrt(y)
Whittaker prefactor, smallest-singular-value dip detection in mpmath dps=30),
parametrized by lambda so the SAME code runs on:
    * SL(2,Z)  (lambda = 1)        -> modular anchor re-validation
    * G_5      (lambda = phi)      -> reproduces the published G_5 r_3
    * G_8      (lambda = 2cos pi/8)-> the new target.

CLAIMS UNDER TEST (from the transfer operator, code/out/zeta_mayer_rosen.json):
    G_8 odd Maass r = 5.798144, 7.767443  (first two odd)
    G_5 odd Maass r_3 = 10.136450         (third odd, secondary)
Eigenvalue lambda_Delta = 1/4 + r^2.

----------------------------------------------------------------------------
THE SURFACE  G_q = (2,q,infinity) Hecke triangle group
----------------------------------------------------------------------------
Generated by
    S : z -> -1/z          (order 2, elliptic fixed pt i)
    T : z -> z + lam       (parabolic, cusp at infinity),  lam = 2 cos(pi/q).
Fundamental domain  F = { |z| >= 1, |Re z| <= lam/2 }.
FD corner (lowest point) at  y = sqrt(1 - (lam/2)^2).
For G_8, lam_8 = 2cos(pi/8) = sqrt(2+sqrt2) ~ 1.8477590650, corner y ~ 0.3827,
so the horocycle height Y0 must sit BELOW 0.3827 (we use ~0.30).

ODD Maass forms (a_{-n} = -a_n):
    u(z) = sqrt(y) sum_{n>=1} a_n K_{ir}(kappa n y) sin(kappa n x),  kappa = 2pi/lam.

----------------------------------------------------------------------------
ALGORITHM (identical to hejhal_g5_maass.py; see that file's docstring).
----------------------------------------------------------------------------
"""

import json
import math
import os
import time

import numpy as np
import mpmath as mp

OUT_PATH = os.path.join(os.path.dirname(__file__), "out", "hejhal_g8_maass.json")


# --------------------------------------------------------------------------
# Surface container -- everything surface-dependent lives here so the SAME
# numerical core runs on lambda = 1 (modular), phi (G_5), 2cos(pi/8) (G_8).
# --------------------------------------------------------------------------
class Surface:
    def __init__(self, lam, name):
        self.lam = float(lam)
        self.name = name
        self.half = self.lam / 2.0
        self.kappa = 2.0 * math.pi / self.lam
        s2 = 1.0 - self.half * self.half
        self.y_corner = math.sqrt(s2) if s2 > 0 else float("nan")


def make_Gq(q):
    return Surface(2.0 * math.cos(math.pi / q), f"G_{q} = (2,{q},inf)")


MODULAR = Surface(1.0, "SL(2,Z) modular")


# --------------------------------------------------------------------------
# 1.  Pullback into the fundamental domain (nearest-lambda reduction + S).
#     Identical algorithm to hejhal_g5_maass.pullback, parametrized by surf.
# --------------------------------------------------------------------------
def pullback(surf, x, y, max_iter=10000):
    lam, half = surf.lam, surf.half
    z = complex(x, y)
    for _ in range(max_iter):
        n = math.floor(z.real / lam + 0.5)
        if n != 0:
            z = complex(z.real - n * lam, z.imag)
        r2 = z.real * z.real + z.imag * z.imag
        if r2 < 1.0 - 1e-15:
            z = -1.0 / z
        else:
            if abs(z.real) <= half + 1e-12:
                return z.real, z.imag
    return z.real, z.imag


# --------------------------------------------------------------------------
# 2.  mpmath column-normalized Hejhal matrix  W(r) = B - C(r)  for ODD forms.
#     Verbatim port of hejhal_g5_maass.build_W_mp with surf-parametrized
#     lambda / kappa / half.  sqrt(y) Whittaker prefactor included.
# --------------------------------------------------------------------------
def build_W_mp(surf, r, M, Y0, Q, dps=30):
    with mp.workdps(dps):
        rr = mp.mpf(r)
        Y0m = mp.mpf(Y0)
        kappa = mp.mpf(surf.kappa)
        half = mp.mpf(surf.half)
        order = mp.mpc(0, rr)

        xs = [half * (mp.mpf(j) - mp.mpf('0.5')) / Q for j in range(1, Q + 1)]
        xs_f = [float(x) for x in xs]
        pb = [pullback(surf, x, Y0) for x in xs_f]
        xstar = [mp.mpf(p[0]) for p in pb]
        ystar = [mp.mpf(p[1]) for p in pb]

        KY0 = [mp.besselk(order, kappa * (n + 1) * Y0m).real for n in range(M)]

        SIN_samp = [[mp.sin(kappa * (n + 1) * xs[j]) for j in range(Q)] for n in range(M)]
        SIN_star = [[mp.sin(kappa * (n + 1) * xstar[j]) for j in range(Q)] for n in range(M)]
        # sqrt(y) Whittaker prefactor: RHS picks up sqrt(y*_j / Y0). Essential.
        sqrt_fac = [mp.sqrt(ystar[j] / Y0m) for j in range(Q)]
        KR = [[mp.besselk(order, kappa * (n + 1) * ystar[j]).real / KY0[n] for j in range(Q)]
              for n in range(M)]
        PHI = [[sqrt_fac[j] * KR[n][j] * SIN_star[n][j] for j in range(Q)] for n in range(M)]

        twoQ = 2 / mp.mpf(Q)
        W = mp.matrix(M, M)
        for l in range(M):
            srow = SIN_samp[l]
            for n in range(M):
                B = mp.mpf(0)
                C = mp.mpf(0)
                sn = SIN_samp[n]
                pn = PHI[n]
                for j in range(Q):
                    slj = srow[j]
                    B += slj * sn[j]
                    C += slj * pn[j]
                W[l, n] = twoQ * (B - C)
        return W


def _is_real(G):
    for i in range(G.rows):
        for j in range(G.cols):
            if abs(mp.im(G[i, j])) > mp.mpf(10) ** (-mp.mp.dps + 5):
                return False
    return True


def _mp_smallest_sv(W):
    n = W.rows
    G = W.H * W
    for i in range(n):
        for j in range(n):
            G[i, j] = (G[i, j] + mp.conj(G[j, i])) / 2
    ev = mp.eigsy(G, eigvals_only=True) if _is_real(G) else mp.eig(G, left=False, right=False)
    vals = [abs(mp.re(e)) for e in ev]
    vals = [v for v in vals if v >= 0]
    smin = mp.sqrt(min(vals))
    smax = mp.sqrt(max(vals))
    return smin, smax


def sigma_min_mp(surf, r, M, Y0, Q, dps=30):
    with mp.workdps(dps):
        W = build_W_mp(surf, r, M, Y0, Q, dps)
        smin, smax = _mp_smallest_sv(W)
        return float(smin), float(smax)


def smin_only(surf, r, M, Y0, Q, dps=30):
    return sigma_min_mp(surf, r, M, Y0, Q, dps)[0]


# --------------------------------------------------------------------------
# 3.  Scan + golden-section refine of the sigma_min dip.
# --------------------------------------------------------------------------
def golden_refine(f, a, b, tol=1e-4, max_iter=40):
    gr = (math.sqrt(5) - 1) / 2
    c = b - gr * (b - a)
    d = a + gr * (b - a)
    fc, fd = f(c), f(d)
    for _ in range(max_iter):
        if abs(b - a) < tol:
            break
        if fc < fd:
            b, d, fd = d, c, fc
            c = b - gr * (b - a)
            fc = f(c)
        else:
            a, c, fc = c, d, fd
            d = a + gr * (b - a)
            fd = f(d)
    rmin = (a + b) / 2
    return rmin, f(rmin)


def locate_dip(surf, target, M, Y0, Q, dps, half_window=0.30, n_grid=25, verbose=True):
    lo, hi = target - half_window, target + half_window
    rr = np.linspace(lo, hi, n_grid)
    vals = []
    for r in rr:
        s = smin_only(surf, float(r), M, Y0, Q, dps)
        vals.append(s)
        if verbose:
            print(f"    r={r:.4f}  sigma_min={s:.4e}", flush=True)
    vals = np.array(vals)
    k = int(np.argmin(vals))
    a = rr[max(0, k - 1)]
    b = rr[min(len(rr) - 1, k + 1)]
    rstar, vstar = golden_refine(lambda r: smin_only(surf, r, M, Y0, Q, dps), a, b,
                                 tol=1e-4, max_iter=40)
    return float(rstar), float(vstar), [[float(r), float(v)] for r, v in zip(rr, vals)]


def auto_M(surf, target, Y0):
    """Truncation: need kappa*M*Y0 comfortably > r so the Fourier tail decays."""
    return int(target / (surf.kappa * Y0)) + 14


# --------------------------------------------------------------------------
# main
# --------------------------------------------------------------------------
def main():
    dps = 30
    results = {
        "method": ("Hejhal automorphy point-matching, ODD (sine) Maass forms; "
                   "indicator = smallest singular value of the column-normalized "
                   "implicit-automorphy matrix W(r)=B-C(r), in mpmath dps=30. "
                   "sqrt(y) Whittaker prefactor included."),
        "independence_note": ("Does NOT use/import the Mayer transfer-operator code. "
                              "Reuses the validated hejhal_g5_maass machinery, "
                              "parametrized by lambda."),
        "surfaces": {},
    }

    # ----------------------------------------------------------------------
    # (A) Modular anchor re-validation (lambda=1).  Known odd r1=9.533695.
    #     Confirms the parametrized code still reproduces the anchor.
    # ----------------------------------------------------------------------
    print("\n=== MODULAR ANCHOR re-validation  (lambda=1, known odd r1=9.533695) ===",
          flush=True)
    surf = MODULAR
    Y0 = 0.65
    target = 9.533695
    M = auto_M(surf, target, Y0)
    Q = 2 * M + 8
    rstar, vstar, grid = locate_dip(surf, target, M, Y0, Q, dps, half_window=0.25, n_grid=21)
    print(f"   --> modular r* = {rstar:.5f}   sigma_min = {vstar:.3e}   "
          f"(known 9.533695, diff={rstar-9.533695:+.5f})", flush=True)
    results["surfaces"]["modular"] = {
        "lambda": surf.lam, "kappa": surf.kappa, "Y0": Y0, "M": M, "Q": Q, "dps": dps,
        "known_r": 9.533695, "r_star": rstar, "sigma_min": vstar,
        "diff": rstar - 9.533695, "scan_grid": grid,
    }

    # ----------------------------------------------------------------------
    # (B) G_8 targets  (lambda_8 = 2cos pi/8 ~ 1.84776, corner y ~ 0.3827).
    #     TO claim: r1=5.798144, r2=7.767443.  Use Y0 ~ 0.30 (below corner).
    #     Height-independence check: re-locate r1 at a second Y0.
    # ----------------------------------------------------------------------
    g8 = make_Gq(8)
    print(f"\n=== G_8  lambda={g8.lam:.10f}  kappa={g8.kappa:.6f}  "
          f"FD corner y={g8.y_corner:.6f} ===", flush=True)
    g8_targets = [5.798144, 7.767443]
    Y0_g8 = 0.30
    g8_located = []
    for target in g8_targets:
        M = auto_M(g8, target, Y0_g8)
        Q = 2 * M + 8
        print(f"\n--- G_8 scan around TO r~{target}  (M={M},Q={Q},Y0={Y0_g8}) ---",
              flush=True)
        rstar, vstar, grid = locate_dip(g8, target, M, Y0_g8, Q, dps,
                                        half_window=0.30, n_grid=25)
        print(f"   --> G_8 r* = {rstar:.5f}   sigma_min = {vstar:.3e}   "
              f"(TO={target}, diff={rstar-target:+.5f})", flush=True)
        g8_located.append({
            "TO_claim": target, "M": M, "Q": Q, "Y0": Y0_g8, "dps": dps,
            "r_star": rstar, "sigma_min": vstar, "diff_from_TO": rstar - target,
            "scan_grid": grid,
        })

    # Height-independence: re-locate r1 at a different Y0 (rules out artifacts).
    Y0_g8_b = 0.24
    t1 = g8_targets[0]
    Mb = auto_M(g8, t1, Y0_g8_b)
    Qb = 2 * Mb + 8
    print(f"\n--- G_8 HEIGHT-INDEPENDENCE check: r1 at Y0={Y0_g8_b} (M={Mb},Q={Qb}) ---",
          flush=True)
    rstar_b, vstar_b, grid_b = locate_dip(g8, t1, Mb, Y0_g8_b, Qb, dps,
                                          half_window=0.20, n_grid=17)
    print(f"   --> G_8 r1 at Y0={Y0_g8_b}: r*={rstar_b:.5f}  sigma_min={vstar_b:.3e}",
          flush=True)
    height_check = {
        "r1_Y0_a": {"Y0": Y0_g8, "r_star": g8_located[0]["r_star"],
                    "sigma_min": g8_located[0]["sigma_min"]},
        "r1_Y0_b": {"Y0": Y0_g8_b, "M": Mb, "Q": Qb, "r_star": rstar_b,
                    "sigma_min": vstar_b, "scan_grid": grid_b},
        "r_star_shift": rstar_b - g8_located[0]["r_star"],
    }

    results["surfaces"]["G_8"] = {
        "lambda": g8.lam, "kappa": g8.kappa, "y_corner": g8.y_corner,
        "TO_claims": g8_targets, "located": g8_located,
        "height_independence": height_check,
    }

    # ----------------------------------------------------------------------
    # (C) G_5 r_3 (secondary).  lambda = phi.  TO claim r_3 = 10.136450.
    # ----------------------------------------------------------------------
    g5 = make_Gq(5)
    print(f"\n=== G_5 r_3  lambda={g5.lam:.10f}  kappa={g5.kappa:.6f} ===", flush=True)
    Y0_g5 = 0.50
    t3 = 10.136450
    M = auto_M(g5, t3, Y0_g5)
    Q = 2 * M + 8
    print(f"--- G_5 scan around TO r_3~{t3}  (M={M},Q={Q},Y0={Y0_g5}) ---", flush=True)
    rstar, vstar, grid = locate_dip(g5, t3, M, Y0_g5, Q, dps, half_window=0.30, n_grid=25)
    print(f"   --> G_5 r_3* = {rstar:.5f}   sigma_min = {vstar:.3e}   "
          f"(TO={t3}, diff={rstar-t3:+.5f})", flush=True)
    results["surfaces"]["G_5_r3"] = {
        "lambda": g5.lam, "kappa": g5.kappa, "Y0": Y0_g5, "M": M, "Q": Q, "dps": dps,
        "TO_claim": t3, "r_star": rstar, "sigma_min": vstar,
        "diff_from_TO": rstar - t3, "scan_grid": grid,
    }

    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    with open(OUT_PATH, "w") as f:
        json.dump(results, f, indent=2)
    print(f"\nWrote {OUT_PATH}")

    print("\n================ SUMMARY ================")
    m = results["surfaces"]["modular"]
    print(f"  MODULAR  known r=9.533695  Hejhal r*={m['r_star']:.5f}  "
          f"diff={m['diff']:+.5f}  sigma_min={m['sigma_min']:.2e}")
    for loc in results["surfaces"]["G_8"]["located"]:
        print(f"  G_8  TO r={loc['TO_claim']:8.5f}  Hejhal r*={loc['r_star']:.5f}  "
              f"diff={loc['diff_from_TO']:+.5f}  sigma_min={loc['sigma_min']:.2e}")
    hc = results["surfaces"]["G_8"]["height_independence"]
    print(f"  G_8  height-indep r1: Y0={hc['r1_Y0_a']['Y0']} -> {hc['r1_Y0_a']['r_star']:.5f} | "
          f"Y0={hc['r1_Y0_b']['Y0']} -> {hc['r1_Y0_b']['r_star']:.5f}  "
          f"shift={hc['r_star_shift']:+.2e}")
    g = results["surfaces"]["G_5_r3"]
    print(f"  G_5  TO r3={g['TO_claim']:8.5f}  Hejhal r*={g['r_star']:.5f}  "
          f"diff={g['diff_from_TO']:+.5f}  sigma_min={g['sigma_min']:.2e}")


if __name__ == "__main__":
    main()
