"""
scout_am_twist_degeneracy.py
============================
DECISIVE test of whether the Taha G_q-BCZ map is a GENUINE monotone twist map
(in the Birkhoff-Mather sense) or only a PIECEWISE-LINEAR parabolic map whose
'twist' is degenerate.

Birkhoff/Mather twist map of the annulus: (theta,r)->(theta',r') generated by
h(theta,theta') with h_{12}=d^2 h/dtheta dtheta' bounded away from 0 CONTINUOUSLY,
equiv. d theta'/d r continuous, nonzero, bounded. The variational (Aubry-Mather)
theory needs this CONTINUOUS, NONDEGENERATE twist + a global generating function.

We test on the raw (a,b) map:
  (T1) Is d a'/d b CONTINUOUS across the domain, or piecewise-constant with JUMPS
       at branch boundaries? (Continuous nondegenerate => genuine twist;
       piecewise-constant => parabolic/projective, NOT a smooth twist map.)
  (T2) Within a branch, the map is a Mobius/affine action of a fixed matrix M_i in
       PSL2; so it is PIECEWISE-PROJECTIVE. The 'twist' d a'/d b = (M_i)_row-derivative
       is CONSTANT on each branch -> the generating function is piecewise-quadratic,
       and the map is NOT C^1 across branch walls. Confirm the JUMP in d a'/d b at a wall.
  (T3) Lyapunov exponent: a monotone twist map in its KAM/Mather regime has positive
       Lyapunov exponent on the minimizing hyperbolic set (Aubry-Mather sets are
       hyperbolic for chaotic twist maps). The BCZ map is ZERO-ENTROPY (horocycle
       section) -> Lyapunov exponent ZERO. Compute it: if ~0, the map is parabolic,
       categorically OUTSIDE the chaotic-twist-map / Aubry-Mather hyperbolic regime.
"""
import math
import numpy as np

def hecke_setup(q):
    lam=2.0*math.cos(math.pi/q)
    U=np.array([[lam,-1.0],[1.0,0.0]])
    w=[np.array([1.0,0.0])]
    for _ in range(q):
        w.append(U@w[-1])
    return lam,w

def bcz_step(a,b,lam,w,q):
    d=[float(w[i]@np.array([a,b])) for i in range(q+1)]
    sub=None
    for i in range(2,q):
        if d[i-1]>1.0 and d[i]<=1.0:
            sub=i; break
    if sub is None:
        for i in range(2,q):
            if d[i]<=1.0:
                sub=i; break
        if sub is None: sub=q-1
    i=sub
    wi=d[i]; wi1=d[i+1]; yi=float(w[i][1])
    P=a*wi/yi
    k=math.floor((1.0-wi1)/(lam*wi))
    a2=wi; b2=wi1+k*lam*wi
    return a2,b2,i,k,P

def jac(a,b,lam,w,q,h=1e-7):
    a0,b0,i0,k0,_=bcz_step(a,b,lam,w,q)
    ax,bx,ix,kx,_=bcz_step(a+h,b,lam,w,q)
    ay,by,iy,ky,_=bcz_step(a,b+h,lam,w,q)
    if (ix,kx)!=(i0,k0) or (iy,ky)!=(i0,k0): return None,i0,k0
    J=np.array([[(ax-a0)/h,(ay-a0)/h],[(bx-b0)/h,(by-b0)/h]])
    return J,i0,k0

print("="*70)
print("T1/T2: is d a'/d b CONTINUOUS or piecewise-constant w/ jumps at walls?")
print("="*70)
for q in [5,7]:
    lam,w=hecke_setup(q)
    # sweep b across the domain at fixed a, record da'/db and branch index
    a=0.55
    print(f"\nq={q} lam={lam:.5f}, fixed a={a}, sweeping b:")
    prev_tw=None; prev_i=None; jumps=0
    bs=np.linspace(max(1e-3,1-lam*a)+1e-3, 1.0-1e-3, 400)
    distinct_vals={}
    for b in bs:
        J,i,k=jac(a,b,lam,w,q)
        if J is None: continue
        tw=J[0,1]
        distinct_vals.setdefault(round(tw,5),0)
        distinct_vals[round(tw,5)]+=1
        if prev_tw is not None and abs(tw-prev_tw)>1e-4:
            jumps+=1
        prev_tw=tw; prev_i=i
    print(f"   distinct values of d a'/d b along the sweep: {sorted(distinct_vals.keys())}")
    print(f"   number of JUMP discontinuities in d a'/d b: {jumps}")
    print(f"   -> {'PIECEWISE-CONSTANT (parabolic/projective, NOT a smooth twist)' if len(distinct_vals)<=q else 'continuous'}")
    print(f"   (a genuine Mather twist map has d a'/db varying CONTINUOUSLY; here it takes only")
    print(f"    finitely many values = Chebyshev/Hecke-vector components, jumping at branch walls)")

print("\n"+"="*70)
print("T3: LYAPUNOV EXPONENT (twist-map KAM regime => >0 on Mather set;")
print("    horocycle section => 0 = parabolic, outside chaotic-twist theory)")
print("="*70)
for q in [3,5,7,12]:
    lam,w=hecke_setup(q)
    rng=np.random.default_rng(5)
    # average top Lyapunov exponent over orbits via product of Jacobians (QR)
    lyaps=[]
    for _ in range(40):
        a=rng.random(); b=rng.random()
        if not(0<a<=1 and (1-lam*a)<b<=1): continue
        for _ in range(100): a,b,i,k,P=bcz_step(a,b,lam,w,q)
        Q=np.eye(2); s=0.0; n=0
        for _ in range(2000):
            J,i,k=jac(a,b,lam,w,q)
            a,b,i,k,P=bcz_step(a,b,lam,w,q)
            if J is None: continue
            M=J@Q
            Qn,R=np.linalg.qr(M)
            s+=math.log(abs(R[0,0])); n+=1
            Q=Qn
        if n>0: lyaps.append(s/n)
    lyaps=np.array(lyaps)
    print(f"q={q} lam={lam:.5f}: top Lyapunov exp = {lyaps.mean():.6f} +/- {lyaps.std():.6f}  "
          f"(n_orbits={len(lyaps)})")
print("\n(If Lyapunov ~ 0 for all q: map is PARABOLIC/zero-entropy -> Aubry-Mather")
print(" *hyperbolic minimizing set* theory does not apply; this is a horocycle section,")
print(" not a chaotic area-preserving twist map.)")
