"""
Lifted-BCZ cross-section simulation for a finite-index subgroup H of PSL(2,Z),
given H as a coset diagram (sig, tau) [transitive, sig^2=tau^3=1 in S_n].

Cross-section dynamics: standard BCZ on the Farey triangle
   F = {(a,b): 0<a<=1, 0<b<=1, a+b>1},  T(a,b)=(b, -a + k b), k=floor((1+a)/b),
return time R=1/(ab), observable P=a*b. We attach a coset label updated by the
parabolic/cusp combinatorics. The H-Farey sub-orbit = returns to a fixed coset
sheet over the cusp; its gap statistic is what Heersink's lift produces.

The coset label transforms under the BCZ step by rho(T_word) where T_word is the
PSL2Z element realizing one BCZ step. One BCZ step corresponds to applying the
parabolic generator T some number of times then the flip S (the BCZ map is
generated by T and S acting on the section). We track the label by composing the
generator permutations accordingly.
"""
import numpy as np
from math import floor

def cycles(p):
    n=len(p); seen=[False]*n; out=[]
    for i in range(n):
        if not seen[i]:
            c=[]; j=i
            while not seen[j]:
                seen[j]=True; c.append(j); j=p[j]
            out.append(c)
    return out
def comp(p,q): return tuple(p[q[i]] for i in range(len(p)))
def inv(p):
    r=[0]*len(p)
    for i,x in enumerate(p): r[x]=i
    return tuple(r)

# ---- BCZ orbit (long), recording (a,b,P) ----
def bcz_orbit(a0,b0,nsteps):
    a,b=a0,b0
    out=[]
    for _ in range(nsteps):
        k=floor((1.0+a)/b)
        a,b = b, -a + k*b
        out.append((a,b,a*b,k))
    return out

# ---- coset label track ----
# In the BCZ generation, each step applies T (parabolic, k times) then S (flip).
# Image perms: L = image of T (=comp(sig,tau)), S_perm = sig.
def track_labels(orbit, sig, tau, start_label=0):
    L = comp(sig,tau)            # image of T
    Spm = sig                    # image of S
    lbl = start_label
    labels=[]
    for (a,b,P,k) in orbit:
        # apply T^k then S to the sheet label
        # acting on right cosets: c -> rho(g)(c); compose k copies of L then S
        for _ in range(k % len(sig)):  # T has finite order on cosets; reduce mod cusp width handled by cycle
            lbl = L[lbl]
        lbl = Spm[lbl]
        labels.append(lbl)
    return labels

def cluster_ceiling_for_coset(orbit, labels, target_coset, X):
    """Longest run of consecutive returns-to-target_coset whose P < X.
    'consecutive returns' = consecutive in the sub-sequence restricted to
    indices where label==target_coset."""
    run=0; best=0
    sub_P=[orbit[i][2] for i in range(len(orbit)) if labels[i]==target_coset]
    for P in sub_P:
        if P < X:
            run+=1; best=max(best,run)
        else:
            run=0
    return best, len(sub_P)

def support_edge(orbit, labels, target_coset):
    sub_P=[orbit[i][2] for i in range(len(orbit)) if labels[i]==target_coset]
    return min(sub_P) if sub_P else None

# ---------------- DEFINE TWO INDEX-7 SUBGROUPS ----------------
# We use coset diagrams. For PSL2Z with s^2=t^3=1.
# Example A (CONGRUENCE): Gamma_0(N)-type. Take the congruence subgroup of index 7
#   = Gamma_0(7) has index 8 actually (psi(7)=8). Use Gamma^0/Gamma_0; instead use
#   a clean congruence index-7? In PSL2Z, smallest congruence indices: Gamma_0(p)
#   index p+1. So index 7 congruence is NOT a Gamma_0(p). But index<7 are all
#   congruence; and there ARE congruence subgroups of index 7 (e.g. a subgroup of
#   Gamma_0(... )). To get a clean matched comparison we instead compare:
#     - index 6: ALWAYS congruence (no noncong below 7). e.g. Gamma_0(5) index 6.
#     - index 7: the famous noncongruence subgroups exist.
# Better matched test: pick TWO index-7 diagrams, classify each by Wohlfahrt level
# + Hsu, report cusp widths & cluster ceilings. We'll just enumerate index-7
# diagrams, group by cusp-width profile, and within a profile compare ceilings.

from collections import defaultdict
import itertools

n=7
# generate all involutions sig (s^2=1) with no... allow fixed pts (cusps of width via t)
def involutions(n):
    # build via pairings
    res=[]
    def rec(elems, cur):
        if not elems:
            p=list(range(n))
            for (i,j) in cur: p[i]=j; p[j]=i
            res.append(tuple(p)); return
        x=elems[0]
        # x fixed
        rec(elems[1:], cur)
        # x paired
        for k in range(1,len(elems)):
            y=elems[k]
            rec(elems[1:k]+elems[k+1:], cur+[(x,y)])
    rec(list(range(n)), [])
    return res

def order3s(n):
    res=[]
    def rec(elems,cur):
        if not elems:
            p=list(range(n))
            for c in cur:
                for i in range(3):
                    p[c[i]]=c[(i+1)%3]
            res.append(tuple(p)); return
        x=elems[0]
        rec(elems[1:],cur)  # x fixed
        rest=elems[1:]
        for i in range(len(rest)):
            for j in range(i+1,len(rest)):
                rec([e for k,e in enumerate(rest) if k!=i and k!=j], cur+[(x,rest[i],rest[j])])
    rec(list(range(n)),[])
    return res

def transitive(gens,n):
    seen=[False]*n; seen[0]=True; st=[0]
    while st:
        x=st.pop()
        for g in gens:
            y=g[x]
            if not seen[y]: seen[y]=True; st.append(y)
    return all(seen)

invs=involutions(n); o3s=order3s(n)
print(f"#involutions={len(invs)} #order3={len(o3s)}")
profiles=defaultdict(list)
count=0
for sig in invs:
    for tau in o3s:
        if not transitive([sig,tau],n): continue
        u=comp(sig,tau)
        ct=tuple(sorted(len(c) for c in cycles(u)))  # cusp widths
        N=int(np.lcm.reduce([len(c) for c in cycles(u)]))
        profiles[ct].append((sig,tau,N))
        count+=1
print("transitive index-7 diagrams:",count)
for ct in sorted(profiles):
    print("cusp-width profile",ct,"  count",len(profiles[ct]))

# ---------------- CONGRUENCE TEST (Hsu 1996, exact for PSL2Z) ----------------
# Hsu's theorem: Let G<=PSL2Z of index n, with L = image of [[1,1],[0,1]] (parabolic T)
# and R = image of [[1,0],[-1,1]] in the coset perm rep. Let m = level = order of L
# (= lcm cusp widths). Then G is congruence iff the following relations hold in <L,R>:
#  Let L,R be the permutations. Write down (depending on m mod 2):
#  - m odd: relation  R = L^c R^? ...  
# We use the standard, widely-implemented form (e.g. in Sage's is_congruence /
# Kulkarni-Hsu): with a,b,c such that a = 2^{-1} mod m etc. To avoid transcription
# error we use the ROBUST equivalent: G is congruence  <=>  the map
#    PSL2(Z) -> Sym(cosets)  factors through PSL2(Z/m).
# Operationally: <L,R> (perm group) is a quotient of PSL2Z; it factors through
# PSL2(Z/m) iff the kernel contains Gamma(m), iff adding the relations of Gamma(m)
# (namely that the principal congruence relations hold) is consistent.
# The cleanest exact certificate: build PSL2(Z/m) explicitly, find its action on
# n points compatible with L=T-image, R-image; congruence iff such compatible
# transitive PSL2(Z/m)-set of size n exists matching (L,R) cycle structure AND
# the abstract group <L,R> is a quotient of PSL2(Z/m).
#
# Simplest rigorous proxy that is SUFFICIENT to separate our pair:
# compute |<sig,tau>| (the monodromy group as a perm group). For congruence
# subgroups of level m, the monodromy group is a quotient of PSL2(Z/m); for the
# famous index-7 NONcongruence ones the monodromy group is A7 or L2(7) etc.
# We report the monodromy group order + composition, plus Wohlfahrt level, which
# together with the literature pins down congruence status.

def perm_group_order(gens, n):
    # BFS over the group generated by gens (and inverses) in S_n
    start=tuple(range(n))
    seen={start}; frontier=[start]
    gl=list(gens)+[inv(g) for g in gens]
    while frontier:
        nf=[]
        for x in frontier:
            for g in gl:
                y=comp(g,x)
                if y not in seen:
                    seen.add(y); nf.append(y)
        frontier=nf
    return len(seen)

# Focus on the single-cusp profile (7,) where the classical noncongruence index-7
# subgroups live. Classify by monodromy group order.
print("\n--- profile (7,): monodromy group orders ---")
from collections import Counter
mono=Counter()
reps={}
for (sig,tau,N) in profiles[(7,)]:
    o=perm_group_order([sig,tau],7)
    mono[o]+=1
    if o not in reps: reps[o]=(sig,tau,N)
for o in sorted(mono):
    print(f"  |monodromy|={o}  count={mono[o]}   (level N={reps[o][2]})")
# PSL2(Z/7) = L2(7) has order 168. A7 has order 2520. S7=5040.

print("\n--- ALL index-7 profiles: monodromy spectrum ---")
for ct in sorted(profiles):
    mono=Counter()
    sample={}
    for (sig,tau,N) in profiles[ct]:
        o=perm_group_order([sig,tau],7)
        mono[o]+=1
        sample.setdefault((o,N),(sig,tau))
    print(f"profile {ct}: "+", ".join(f"|G|={o}(N={[k[1] for k in sample if k[0]==o][0]}):{c}" for o,c in sorted(mono.items())))

# Congruence test via Wohlfahrt+monodromy: a transitive PSL2Z action of index n
# and level N is CONGRUENCE iff its monodromy is a quotient of PSL2(Z/N).
# |PSL2(Z/N)|: N=2:6, 3:12, 4:48, 5:60, 6:72(=PSL2(2)xPSL2(3)? CRT 6*... ), 7:168.
def psl2_modN_order(N):
    # |SL2(Z/N)| = N^3 prod_{p|N}(1-1/p^2); PSL2 = that /2 for N>2, /1 for N=2
    from sympy import primefactors
    sl=N**3
    for p in primefactors(N):
        sl = sl*(p*p-1)//(p*p)
    return sl if N<=2 else sl//2

for N in [2,3,4,5,6,7,12]:
    print(f"|PSL2(Z/{N})| = {psl2_modN_order(N)}")

print("\n=================  LIFTED-BCZ CROSS-SECTION CLUSTER CEILING  =================")
# Pick representatives:
#   CONG  = profile (7,)  monodromy L2(7)=168, level 7  -> congruence
#   NONC  = profile (1,6) monodromy order 42, level 6   -> NON-congruence (7 nmid 72)
cong_sig, cong_tau, cong_N = reps[168] if 168 in reps else profiles[(7,)][0][:2]+(7,)
cong = profiles[(7,)][0]
nonc = profiles[(1,6)][0]
print("CONG rep level", cong[2], "cusp widths", tuple(sorted(len(c) for c in cycles(comp(cong[0],cong[1])))))
print("NONC rep level", nonc[2], "cusp widths", tuple(sorted(len(c) for c in cycles(comp(nonc[0],nonc[1])))))

# long BCZ orbit
np.random.seed(20260614)
a0=0.61803398875; b0=0.7  # generic start on/near triangle
# ensure on triangle:
if a0+b0<=1: b0=1-a0+0.3
orbit=bcz_orbit(a0,b0,400000)
# drop transient
orbit=orbit[100:]

def analyze(sig,tau,name):
    labels=track_labels(orbit, sig, tau)
    n=len(sig)
    print(f"\n[{name}] coset-label distribution:", Counter(labels))
    # support edge of FULL section (no coset restriction) = global BCZ edge
    # For each coset sheet compute support edge and cluster ceiling at that edge*(1+eps)
    results=[]
    for c in range(n):
        edge=support_edge(orbit,labels,c)
        if edge is None: continue
        # cluster ceiling = longest run with P below a small quantile threshold X.
        # Use the GLOBAL section onset analogue: X = edge*1.0001 won't give runs;
        # use the extreme-gap onset = the 0.5% quantile of the sub-orbit P's as the
        # "rare small-gap" threshold, mirroring the Hecke cluster definition (P<X).
        subP=np.array([orbit[i][2] for i in range(len(orbit)) if labels[i]==c])
        X=np.quantile(subP,0.01)
        B,m=cluster_ceiling_for_coset(orbit,labels,c,X)
        results.append((c,edge,X,B,m))
    for (c,edge,X,B,m) in results:
        print(f"   coset {c}: support_edge={edge:.6f}  X(1%q)={X:.6f}  ceiling B={B}  (#returns={m})")
    Bmax=max(r[3] for r in results)
    edges=[r[1] for r in results]
    print(f"   --> MAX cluster ceiling over cosets = {Bmax};  min support edge = {min(edges):.6f}")
    return Bmax, min(edges)

cB,cE=analyze(cong[0],cong[1],"CONGRUENCE (7,)  L2(7) level7")
nB,nE=analyze(nonc[0],nonc[1],"NON-CONG (1,6) order42 level6")
print(f"\nSUMMARY: ceiling cong={cB}  noncong={nB}   support-edge cong={cE:.5f} noncong={nE:.5f}")

print("\n=== Independent congruence certificate (Wohlfahrt level + monodromy divisibility) ===")
# A transitive index-n PSL2Z-set of level N is congruence  =>  monodromy is a
# quotient of PSL2(Z/N), hence |monodromy| divides |PSL2(Z/N)|.
# Contrapositive: |monodromy| does NOT divide |PSL2(Z/N)|  =>  NON-CONGRUENCE.
from sympy import primefactors
def psl2_modN_order(N):
    sl=N**3
    for p in primefactors(N):
        sl=sl*(p*p-1)//(p*p)
    return sl if N<=2 else sl//2
for ct,(sig,tau,N) in [((1,6),profiles[(1,6)][0]), ((7,),profiles[(7,)][0]),
                       ((2,5),profiles[(2,5)][0]), ((3,4),profiles[(3,4)][0])]:
    o=perm_group_order([sig,tau],7)
    PN=psl2_modN_order(N)
    div = (PN % o == 0)
    verdict = "CONGRUENCE-compatible" if div else "*** NON-CONGRUENCE (certified) ***"
    print(f"profile {ct}: level N={N}, |monodromy|={o}, |PSL2(Z/{N})|={PN}, "
          f"{o}|{PN}? {div}  -> {verdict}")
