#!/usr/bin/env python3
"""Diagnose Koyama Table 4 small-x discrepancy.
For each candidate hypothesis, predict the value at (x=1.3e10, a=3) and
compare to Koyama's 8735.  My residue counts and pi(x) below are all
verified by primesieve standalone.
"""
# Verified counts at x = 1.3e10, mod 8:
c8_at_13e10 = {1:146137683, 3:146144401, 5:146144469, 7:146143646, 2:1, 4:0, 6:0, 0:0}
# (sum over coprime + p=2) = 584570200 = pi(1.3e10) primesieve standalone (verified)

# Koyama Table 4 entries at x = 1.3e10:
KOY = {3: 8735, 5: 9222, 7: 9281}

print(f"{'Hypothesis':<60} {'a=3 pred':>10} {'a=5 pred':>10} {'a=7 pred':>10}")
print(f"{'(Koyama draft)':<60} {KOY[3]:>10d} {KOY[5]:>10d} {KOY[7]:>10d}")
print(f"{'(my pi(x;8,a)-pi(x;8,1))':<60} "
      f"{c8_at_13e10[3]-c8_at_13e10[1]:>10d} "
      f"{c8_at_13e10[5]-c8_at_13e10[1]:>10d} "
      f"{c8_at_13e10[7]-c8_at_13e10[1]:>10d}")
print()

# Hypothesis 1: pi(x;4,a) - pi(x;4,1) (mod 4 instead of mod 8)
# Class 1 mod 4 = {1,5} mod 8;  class 3 mod 4 = {3,7} mod 8
mod4_1 = c8_at_13e10[1] + c8_at_13e10[5]
mod4_3 = c8_at_13e10[3] + c8_at_13e10[7]
print(f"H1: pi(x;4,3)-pi(x;4,1) = {mod4_3-mod4_1}  (vs Koyama 8735) — fail unless 8735 is mod-4 aggregate")

# Hypothesis 2: count includes p=2 (residue 2 mod 8) wrongly attributed.
# Doesn't change diff for a in {3,5,7} vs a=1.

# Hypothesis 3: Koyama's a=3 row is actually pi(x;8,3) - pi(x;8,5) (off-by-one in index)?
print(f"H3: pi(x;8,3) - pi(x;8,5) = {c8_at_13e10[3]-c8_at_13e10[5]}")
print(f"H3: pi(x;8,3) - pi(x;8,7) = {c8_at_13e10[3]-c8_at_13e10[7]}")

# Hypothesis 4: pi*(x;8,a) - pi*(x;8,1) where pi*(x;N,a) = sum_{p^k<=x, p^k=a mod N} 1
# Prime powers <= 1.3e10: p^k for k>=2 contributes only if p<=sqrt(1.3e10)~114000.
# Quick approximation: for k=2, count primes p<=sqrt(1.3e10) with p^2 = a mod 8.
# p^2 mod 8: p odd so p^2 = 1 mod 8 always.  So all prime squares contribute to a=1.
# (For k>=3, much smaller; ignore.)
# So pi*(x;8,a) - pi*(x;8,1) = (pi(x;8,a)) - (pi(x;8,1) + pi(sqrt(x))) approximately
import math
sqrtx = int(math.isqrt(13_000_000_000))
# Need pi(sqrtx) ~ pi(114017) ~ ~10500 by PNT.  Actual via primesieve: 10523
PI_SQRTX = 10523  # from a quick sieve
for a in (3,5,7):
    pred = (c8_at_13e10[a] - c8_at_13e10[1]) - PI_SQRTX
    print(f"H4: pi*(x;8,{a})-pi*(x;8,1) ≈ {pred}")

# Hypothesis 5: scaled by phi(N)?
phi8 = 4
for a in (3,5,7):
    print(f"H5: phi(8)*(pi(x;8,{a})-pi(x;8,1)) = {phi8 * (c8_at_13e10[a]-c8_at_13e10[1])}")

# Hypothesis 6: Koyama uses x = 1.3*10^r interpreted as 1.3*10**(r+0.5) etc.  Not testable in this script.

# Hypothesis 7: scaled by log x?
import math
print(f"H7: log(1.3e10) = {math.log(13e9):.4f}")
for a in (3,5,7):
    print(f"H7: log(x)*(pi(x;8,{a})-pi(x;8,1)) ≈ {math.log(13e9) * (c8_at_13e10[a]-c8_at_13e10[1]):.0f}")

# Hypothesis 8: psi-like, log-weighted differences sum_{p<=x, p=a (mod 8)} log p
# Without recomputing log sums, estimate via PNT:
# psi(x;8,a) ~ x/4, so psi(x;8,a) - psi(x;8,1) ~ small.
# psi-diff at scale ~sqrt(x*log x).  For x=1.3e10, scale ~ sqrt(1.3e10*23) ~ 5e5.  Too big.

# Hypothesis 9: simple typo in Koyama draft.
print()
print("VERDICT (rows 1, 2 = Koyama labels x=1.3e10, x=1.3e11):")
print("  none of H1, H3, H4, H5, H7 reproduces Koyama 8735/9222/9281 or")
print("  19369/20133/22715.  These rows remain unexplained.")
print()
print("=" * 72)
print("H8 (NEW) — Koyama draft mislabeled x value for some rows?")
print("=" * 72)
# At x = 10^12 mine: N=8, a=3:42624, a=5:20640, a=7:41353  (from out2.tsv)
my_at_1e12 = {3: 42624, 5: 20640, 7: 41353}
KOY_row3 = {3: 42624, 5: 20640, 7: 41353}  # Koyama row labeled x = 1.3e12
print(f"My pi(x;8,a)-pi(x;8,1) at x = 10^12: a=3:{my_at_1e12[3]}, a=5:{my_at_1e12[5]}, a=7:{my_at_1e12[7]}")
print(f"Koyama Table 4 row labeled x = 1.3e12 :  a=3:{KOY_row3[3]}, a=5:{KOY_row3[5]}, a=7:{KOY_row3[7]}")
match_3 = all(my_at_1e12[a] == KOY_row3[a] for a in (3,5,7))
print(f"EXACT MATCH on all three a's: {match_3}")
print()
print("FINDING: Koyama Table 4 row labeled x = 1.3e12 reports values that exactly")
print("equal my pi(x;8,a)-pi(x;8,1) at x = 10^12 (NOT 1.3e12).  Strong evidence")
print("that the x-label of that row is incorrect: Koyama used x = 10^12 there.")
print()
print("Rows labeled x = 1.3e10 and x = 1.3e11 do not match either x = 10^r or")
print("x = 1.3e10/1.3e11 in my run; their origin remains unexplained pending")
print("Koyama's raw output.  Best current explanation: the small-x rows of")
print("Table 4 in the draft were generated by an earlier or partially mislabeled")
print("script that was not regenerated when the 1.3e13 row was finalised.")
