#!/usr/bin/env python3
"""
Probe T2 — shape checks for the (T2) two-variable-determinant question.

NON-RIGOROUS throughout (float64 / mpmath, no interval arithmetic, no
certificates).  Three independent checks:

  P1  Fixed-disc invariance test for the UNREDUCED Rosen transfer operator
      L_{s,lam} f(z) = sum_{|n|>=1} ((z+n lam)^2)^{-s} f(-1/(z+n lam)).
      Question: is there ANY disc D containing [-lam/2, lam/2] with
      psi_n(cl D) subset D for all |n| >= 1, for lam in (lam_0, 2]?
      Reported as: the psi_1-orbit of the interval endpoint, and the
      contraction ratio of the n=1 branch.

  P2  Length-spectrum convergence  G_q -> Gamma_theta.
      Enumerate primitive hyperbolic conjugacy classes of G_q = Z/2 * Z/q
      (generated by S and R = S T_lam, R elliptic of order q) and of
      Gamma_theta = Z/2 * Z (R = S T_2 parabolic), by BFS in the group ball,
      canonicalising the free-product normal form up to cyclic rotation.
      Compare the length spectra below a cutoff L.

  P3  Truncated Selberg Euler product  Z_q(s) -> Z_theta(s) for Re s > 1,
      evaluated at s near Im = 7.0674 (the height of s_inf = rho_1/2).

Usage:  python3 probe_t2_shape.py [--L 5.0] [--out t2_shape.json]
"""
from __future__ import annotations

import argparse
import cmath
import json
import math
from typing import Dict, List, Tuple

# ----------------------------------------------------------------------
# matrices as 4-tuples (a,b,c,d), det = 1, PSL(2,R) (sign-normalised)
# ----------------------------------------------------------------------


def mul(x, y):
    a, b, c, d = x
    e, f, g, h = y
    return (a * e + b * g, a * f + b * h, c * e + d * g, c * f + d * h)


def norm2(x):
    return x[0] * x[0] + x[1] * x[1] + x[2] * x[2] + x[3] * x[3]


def normalise_sign(x):
    """PSL(2,R): identify M and -M.  Pick the representative whose first
    nonzero entry (reading a,b,c,d) is positive."""
    for v in x:
        if abs(v) > 1e-12:
            return x if v > 0 else (-x[0], -x[1], -x[2], -x[3])
    return x


def key_of(x, digits=9):
    y = normalise_sign(x)
    return tuple(round(v, digits) for v in y)


S = (0.0, -1.0, 1.0, 0.0)


def R_of(lam):
    # R = S * T_lam,  T_lam = [[1,lam],[0,1]]
    return mul(S, (1.0, lam, 0.0, 1.0))


# ----------------------------------------------------------------------
# P1 — fixed-disc invariance for the unreduced operator
# ----------------------------------------------------------------------


def p1_fixed_disc(lams: List[float]) -> List[dict]:
    """For each lam: report (i) the fixed points of psi_1(z) = -1/(z+lam),
    (ii) |psi_1'| at the interval endpoint -lam/2, (iii) the forward
    psi_1-orbit of -lam/2 (does it leave every bounded disc?), and
    (iv) the full-branch threshold n >= 1/2 + 2/lam^2."""
    out = []
    for lam in lams:
        disc = lam * lam - 4.0
        # psi_1 fixed points solve z^2 + lam z + 1 = 0
        if disc < 0:
            r = math.sqrt(-disc) / 2.0
            fp = f"{-lam/2:.6f} +/- {r:.6f}i (elliptic, rot angle {math.degrees(math.acos(lam/2)):.4f} deg)"
        else:
            fp = f"{-lam/2:.6f} (double, PARABOLIC)"
        # derivative of psi_1 at the left endpoint of the interval
        z0 = -lam / 2.0
        dpsi = 1.0 / (z0 + lam) ** 2
        # forward orbit of the endpoint under psi_1 (real Moebius, may hit inf)
        orb = []
        z = z0
        for _ in range(40):
            den = z + lam
            if abs(den) < 1e-13:
                orb.append(float("inf"))
                break
            z = -1.0 / den
            orb.append(z)
        thr = 0.5 + 2.0 / (lam * lam)
        out.append(
            dict(
                lam=lam,
                q_equiv=(math.pi / math.acos(lam / 2.0)) if lam < 2 else float("inf"),
                psi1_fixed_points=fp,
                dpsi1_at_endpoint=dpsi,
                orbit_max_abs=max(abs(v) for v in orb),
                orbit_first10=[round(v, 6) if math.isfinite(v) else None for v in orb[:10]],
                full_branch_threshold=thr,
            )
        )
    return out


def p1b_orbit_at_lam_q(qs: List[int]) -> List[dict]:
    """At the GROUP values lam = lam_q, psi_1 is elliptic of order q and the
    orbit of the interval endpoint -lam/2 starts antipodal to infinity in the
    rotation coordinate.  Prediction: for even q the orbit hits infinity at
    k = q/2 exactly; for odd q it misses and its max modulus is lam + 1."""
    out = []
    for q in qs:
        lam = 2.0 * math.cos(math.pi / q)
        z = -lam / 2.0
        mx = abs(z)
        hit = None
        for k in range(1, 3 * q + 1):
            den = z + lam
            if abs(den) < 1e-10:
                hit = k
                mx = float("inf")
                break
            z = -1.0 / den
            mx = max(mx, abs(z))
        out.append(dict(q=q, lam=lam, pole_at_k=hit, q_over_2=(q // 2 if q % 2 == 0 else None),
                        orbit_max=mx, lam_plus_1=lam + 1.0))
    return out


# ----------------------------------------------------------------------
# P2/P3 — free-product normal form, BFS ball, conjugacy classes
# ----------------------------------------------------------------------
# Normal form: alternating word in <S> (order 2) and <R> (order q, or inf).
# Encoded as a tuple of syllables; syllable 0 means S, syllable a != 0 means
# R^a.  Adjacent syllables always alternate type.


def reduce_exp(a: int, order: int) -> int:
    """Reduce an R-exponent mod `order` into the symmetric range; 0 = identity."""
    if order == 0:  # infinite order
        return a
    a %= order
    if a > order // 2:
        a -= order
    return a


def right_mul_S(w: Tuple[int, ...]) -> Tuple[int, ...]:
    if w and w[-1] == 0:
        return w[:-1]
    return w + (0,)


def right_mul_R(w: Tuple[int, ...], e: int, order: int) -> Tuple[int, ...]:
    if w and w[-1] != 0:
        a = reduce_exp(w[-1] + e, order)
        return w[:-1] if a == 0 else w[:-1] + (a,)
    a = reduce_exp(e, order)
    return w if a == 0 else w + (a,)


def cyclic_reduce(w: Tuple[int, ...]) -> Tuple[int, ...]:
    """Cyclically reduce: while first and last syllables have the same type,
    fold them together (conjugation by the last syllable)."""
    w = list(w)
    order_free = None  # exponents already reduced; folding may need re-reduction
    changed = True
    while changed and len(w) > 1:
        changed = False
        if (w[0] == 0) == (w[-1] == 0):
            if w[0] == 0:  # both S: S ... S -> ...
                w = w[1:-1]
            else:  # both R-type: fold exponents
                a = w[0] + w[-1]
                w = w[1:-1]
                if a != 0:
                    w = [a] + w
            changed = True
    return tuple(w)


def canonical_cyclic(w: Tuple[int, ...], order: int) -> Tuple[int, ...]:
    """Canonical representative of the cyclic class (conjugacy class)."""
    if not w:
        return ()
    # re-reduce exponents after folding
    w = tuple(0 if x == 0 else reduce_exp(x, order) for x in w)
    w = tuple(x for x in w if True)
    n = len(w)
    rots = [w[i:] + w[:i] for i in range(n)]
    # only rotations that keep the alternating structure are group-conjugates,
    # but for an alternating cyclic word every even rotation works; take the
    # lexicographic minimum over all rotations that are themselves alternating
    good = []
    for r in rots:
        ok = all((r[i] == 0) != (r[i + 1] == 0) for i in range(len(r) - 1))
        if len(r) > 1:
            ok = ok and ((r[0] == 0) != (r[-1] == 0))
        if ok:
            good.append(r)
    return min(good) if good else min(rots)


def is_primitive_cyclic(w: Tuple[int, ...]) -> bool:
    n = len(w)
    for d in range(1, n):
        if n % d == 0 and w == w[:d] * (n // d):
            return False
    return True


def enumerate_classes(lam: float, order: int, rmax: float) -> Dict[Tuple[int, ...], float]:
    """BFS the group ball {g : ||g||_F^2 <= 2 cosh(rmax)} and return
    {canonical primitive cyclic word -> translation length}."""
    Rm = R_of(lam)
    Rinv = (Rm[3], -Rm[1], -Rm[2], Rm[0])
    cap = 2.0 * math.cosh(rmax)
    start = ((1.0, 0.0, 0.0, 1.0), ())
    seen = {key_of(start[0]): ()}
    frontier = [start]
    elements: List[Tuple[Tuple[float, ...], Tuple[int, ...]]] = [start]
    while frontier:
        nxt = []
        for M, w in frontier:
            for gen, we in ((S, "S"), (Rm, +1), (Rinv, -1)):
                M2 = mul(M, gen)
                if norm2(M2) > cap:
                    continue
                w2 = right_mul_S(w) if we == "S" else right_mul_R(w, we, order)
                k = key_of(M2)
                if k in seen:
                    continue
                seen[k] = w2
                nxt.append((M2, w2))
                elements.append((M2, w2))
        frontier = nxt
    classes: Dict[Tuple[int, ...], float] = {}
    for M, w in elements:
        tr = abs(M[0] + M[3])
        if tr <= 2.0 + 1e-9:
            continue
        cw = cyclic_reduce(w)
        if not cw:
            continue
        cw = canonical_cyclic(cw, order)
        if not is_primitive_cyclic(cw):
            continue
        ell = 2.0 * math.acosh(tr / 2.0)
        prev = classes.get(cw)
        if prev is None or ell < prev:
            classes[cw] = ell
    return classes


def p2_length_spectra(qs: List[int], L: float, rmax: float) -> dict:
    res = {}
    theta = enumerate_classes(2.0, 0, rmax)
    theta_l = sorted(v for v in theta.values() if v <= L)
    res["theta"] = dict(n_classes=len(theta_l), lengths=[round(v, 6) for v in theta_l])
    for q in qs:
        lam = 2.0 * math.cos(math.pi / q)
        cl = enumerate_classes(lam, q, rmax)
        ls = sorted(v for v in cl.values() if v <= L)
        # Hausdorff-style comparison against the theta spectrum
        if theta_l and ls:
            d_fwd = max(min(abs(a - b) for b in theta_l) for a in ls)
            d_bwd = max(min(abs(a - b) for a in ls) for b in theta_l)
            haus = max(d_fwd, d_bwd)
        else:
            haus = None
        res[str(q)] = dict(
            lam=lam,
            n_classes=len(ls),
            systole=(min(cl.values()) if cl else None),
            hausdorff_to_theta=haus,
            lengths=[round(v, 6) for v in ls],
        )
    res["theta_systole"] = min(theta.values()) if theta else None
    return res


def selberg_trunc(classes: Dict[Tuple[int, ...], float], s: complex, L: float, kmax: int = 12) -> complex:
    """Truncated Selberg Euler product over primitive classes of length <= L."""
    z = 1.0 + 0j
    for ell in classes.values():
        if ell > L:
            continue
        for k in range(kmax + 1):
            z *= 1.0 - cmath.exp(-(s + k) * ell)
    return z


def p3_zeta(qs: List[int], svals: List[complex], L: float, rmax: float) -> dict:
    out = {}
    theta = enumerate_classes(2.0, 0, rmax)
    for s in svals:
        key = f"{s.real}+{s.imag}i"
        row = {"theta": [selberg_trunc(theta, s, L).real, selberg_trunc(theta, s, L).imag]}
        for q in qs:
            lam = 2.0 * math.cos(math.pi / q)
            cl = enumerate_classes(lam, q, rmax)
            v = selberg_trunc(cl, s, L)
            zt = selberg_trunc(theta, s, L)
            row[str(q)] = [v.real, v.imag, abs(v - zt)]
        out[key] = row
    return out


# ----------------------------------------------------------------------


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--L", type=float, default=5.0, help="geodesic length cutoff")
    ap.add_argument("--rmax", type=float, default=8.0, help="BFS ball radius")
    ap.add_argument("--out", default="t2_shape.json")
    a = ap.parse_args()

    lams = [1.618033988749895, 1.8, 1.9, 1.95, 1.99, 2.0]
    p1 = p1_fixed_disc(lams)
    p1b = p1b_orbit_at_lam_q([5, 7, 8, 10, 12, 14, 20, 22, 30, 50])

    qs = [5, 7, 10, 14, 20, 30, 50, 80]
    p2 = p2_length_spectra(qs, a.L, a.rmax)
    svals = [complex(1.5, 7.0673625708673465), complex(2.0, 0.0), complex(1.2, 7.0673625708673465)]
    p3 = p3_zeta(qs, svals, a.L, a.rmax)

    doc = dict(params=dict(L=a.L, rmax=a.rmax, qs=qs, lams=lams), P1=p1, P1b=p1b, P2=p2, P3=p3)
    with open(a.out, "w") as f:
        json.dump(doc, f, indent=1, default=str)

    print("=== P1  unreduced fixed-disc invariance ===")
    for r in p1:
        print(
            f"lam={r['lam']:.6f}  q~{r['q_equiv']:.2f}  |psi1'(-lam/2)|={r['dpsi1_at_endpoint']:.6f}  "
            f"orbit_max|.|={r['orbit_max_abs']:.4g}  full-branch n>= {r['full_branch_threshold']:.4f}"
        )
        print(f"    psi1 fixed points: {r['psi1_fixed_points']}")
    print()
    print("=== P1b  psi_1-orbit of -lam/2 at the GROUP values lam = lam_q ===")
    for r in p1b:
        tag = f"POLE (-> infinity) at k={r['pole_at_k']} (q/2={r['q_over_2']})" if r["pole_at_k"] \
            else f"bounded, max={r['orbit_max']:.6f}  (lam+1 = {r['lam_plus_1']:.6f})"
        print(f"  q={r['q']:3d} lam={r['lam']:.6f}  {tag}")
    print()
    print("=== P2  length spectra (cutoff L=%.2f) ===" % a.L)
    print(f"  theta: {p2['theta']['n_classes']} classes, systole={p2['theta_systole']:.6f}")
    print(f"    {p2['theta']['lengths'][:12]}")
    for q in qs:
        r = p2[str(q)]
        print(
            f"  q={q:3d} lam={r['lam']:.6f}  n={r['n_classes']:3d}  sys={r['systole']:.6f}  "
            f"Hausdorff-to-theta={r['hausdorff_to_theta']:.6g}"
        )
        print(f"    {r['lengths'][:12]}")
    print()
    print("=== P3  truncated Selberg product ===")
    for k, row in p3.items():
        print(f"  s = {k}   Z_theta = {row['theta'][0]:.8f} + {row['theta'][1]:.8f}i")
        for q in qs:
            v = row[str(q)]
            print(f"    q={q:3d}  Z_q = {v[0]:.8f} + {v[1]:.8f}i   |Z_q - Z_theta| = {v[2]:.4e}")
    print()
    print("wrote", a.out)


if __name__ == "__main__":
    main()
